/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiV1TeacherPingResponse200 = {
  data: void
  status: 200
}

export type getApiV1TeacherPingResponse401 = {
  data: void
  status: 401
}

export type getApiV1TeacherPingResponse403 = {
  data: void
  status: 403
}

export type getApiV1TeacherPingResponseSuccess = (getApiV1TeacherPingResponse200) & {
  headers: Headers;
};
export type getApiV1TeacherPingResponseError = (getApiV1TeacherPingResponse401 | getApiV1TeacherPingResponse403) & {
  headers: Headers;
};

export type getApiV1TeacherPingResponse = (getApiV1TeacherPingResponseSuccess | getApiV1TeacherPingResponseError)

export const getGetApiV1TeacherPingUrl = () => {




  return `/api/v1/teacher/ping`
}

/**
 * Проверяет, что Bearer-токен содержит роль Teacher.
 * @summary Проверка доступа преподавателя
 */
export const getApiV1TeacherPing = async ( options?: Parameters<typeof educationFetch>[1]): Promise<getApiV1TeacherPingResponse> => {

  return educationFetch<getApiV1TeacherPingResponse>(getGetApiV1TeacherPingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1TeacherPingQueryKey = () => {
    return [
    `/api/v1/teacher/ping`
    ] as const;
    }


export const getGetApiV1TeacherPingQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1TeacherPingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TeacherPing>>> = ({ signal }) => getApiV1TeacherPing({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1TeacherPingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1TeacherPing>>>
export type GetApiV1TeacherPingQueryError = void


export function useGetApiV1TeacherPing<TData = Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TeacherPing>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TeacherPing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TeacherPing<TData = Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1TeacherPing>>,
          TError,
          Awaited<ReturnType<typeof getApiV1TeacherPing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1TeacherPing<TData = Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Проверка доступа преподавателя
 */

export function useGetApiV1TeacherPing<TData = Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1TeacherPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1TeacherPingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






