/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateModuleRequest,
  HttpValidationProblemDetails,
  ModuleResponse,
  TheoryListItemResponse
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createModuleResponse200 = {
  data: ModuleResponse
  status: 200
}

export type createModuleResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createModuleResponse401 = {
  data: void
  status: 401
}

export type createModuleResponse403 = {
  data: void
  status: 403
}

export type createModuleResponse404 = {
  data: void
  status: 404
}

export type createModuleResponseSuccess = (createModuleResponse200) & {
  headers: Headers;
};
export type createModuleResponseError = (createModuleResponse400 | createModuleResponse401 | createModuleResponse403 | createModuleResponse404) & {
  headers: Headers;
};

export type createModuleResponse = (createModuleResponseSuccess | createModuleResponseError)

export const getCreateModuleUrl = () => {




  return `/api/v1/modules`
}

/**
 * Создаёт модуль внутри курса преподавателя.
 * @summary Создание модуля
 */
export const createModule = async (createModuleRequest: CreateModuleRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createModuleResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createModuleResponse>(getCreateModuleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createModuleRequest)
  }
);}





export const getCreateModuleMutationKey = () => ['createModule'] as const;

export const getCreateModuleMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createModule>>, TError,CreateModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createModule>>, TError,CreateModuleMutationVariables, TContext> => {

const mutationKey = getCreateModuleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createModule>>, CreateModuleMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createModule(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateModuleMutationResult = NonNullable<Awaited<ReturnType<typeof createModule>>>
    export type CreateModuleMutationBody = CreateModuleRequest
    export type CreateModuleMutationError = HttpValidationProblemDetails | void
    export type CreateModuleMutationVariables = {data: CreateModuleRequest}

    /**
 * @summary Создание модуля
 */
export const useCreateModule = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createModule>>, TError,CreateModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createModule>>,
        TError,
        CreateModuleMutationVariables,
        TContext
      > => {
      return useMutation(getCreateModuleMutationOptions(options), queryClient);
    }
    export type deleteModuleResponse204 = {
  data: void
  status: 204
}

export type deleteModuleResponse401 = {
  data: void
  status: 401
}

export type deleteModuleResponse403 = {
  data: void
  status: 403
}

export type deleteModuleResponse404 = {
  data: void
  status: 404
}

export type deleteModuleResponseSuccess = (deleteModuleResponse204) & {
  headers: Headers;
};
export type deleteModuleResponseError = (deleteModuleResponse401 | deleteModuleResponse403 | deleteModuleResponse404) & {
  headers: Headers;
};

export type deleteModuleResponse = (deleteModuleResponseSuccess | deleteModuleResponseError)

export const getDeleteModuleUrl = (moduleId: string,) => {




  return `/api/v1/modules/${moduleId}`
}

/**
 * Удаляет модуль курса преподавателя.
 * @summary Удаление модуля
 */
export const deleteModule = async (moduleId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deleteModuleResponse> => {

  return educationFetch<deleteModuleResponse>(getDeleteModuleUrl(moduleId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteModuleMutationKey = () => ['deleteModule'] as const;

export const getDeleteModuleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,DeleteModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,DeleteModuleMutationVariables, TContext> => {

const mutationKey = getDeleteModuleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteModule>>, DeleteModuleMutationVariables> = (props) => {
          const {moduleId} = props ?? {};

          return  deleteModule(moduleId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteModuleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteModule>>>

    export type DeleteModuleMutationError = void
    export type DeleteModuleMutationVariables = {moduleId: string}

    /**
 * @summary Удаление модуля
 */
export const useDeleteModule = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteModule>>, TError,DeleteModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteModule>>,
        TError,
        DeleteModuleMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteModuleMutationOptions(options), queryClient);
    }
    export type getModuleTheoriesResponse200 = {
  data: TheoryListItemResponse[]
  status: 200
}

export type getModuleTheoriesResponse401 = {
  data: void
  status: 401
}

export type getModuleTheoriesResponse403 = {
  data: void
  status: 403
}

export type getModuleTheoriesResponseSuccess = (getModuleTheoriesResponse200) & {
  headers: Headers;
};
export type getModuleTheoriesResponseError = (getModuleTheoriesResponse401 | getModuleTheoriesResponse403) & {
  headers: Headers;
};

export type getModuleTheoriesResponse = (getModuleTheoriesResponseSuccess | getModuleTheoriesResponseError)

export const getGetModuleTheoriesUrl = (moduleId: string,) => {




  return `/api/v1/modules/${moduleId}/theories`
}

/**
 * Возвращает теоретические материалы выбранного модуля.
 * @summary Получение теории модуля
 */
export const getModuleTheories = async (moduleId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getModuleTheoriesResponse> => {

  return educationFetch<getModuleTheoriesResponse>(getGetModuleTheoriesUrl(moduleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetModuleTheoriesQueryKey = (moduleId: string,) => {
    return [
    `/api/v1/modules/${moduleId}/theories`
    ] as const;
    }


export const getGetModuleTheoriesQueryOptions = <TData = Awaited<ReturnType<typeof getModuleTheories>>, TError = void>(moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTheories>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModuleTheoriesQueryKey(moduleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleTheories>>> = ({ signal }) => getModuleTheories(moduleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: moduleId !== null && moduleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModuleTheories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModuleTheoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getModuleTheories>>>
export type GetModuleTheoriesQueryError = void


export function useGetModuleTheories<TData = Awaited<ReturnType<typeof getModuleTheories>>, TError = void>(
 moduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTheories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleTheories>>,
          TError,
          Awaited<ReturnType<typeof getModuleTheories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleTheories<TData = Awaited<ReturnType<typeof getModuleTheories>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTheories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleTheories>>,
          TError,
          Awaited<ReturnType<typeof getModuleTheories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleTheories<TData = Awaited<ReturnType<typeof getModuleTheories>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTheories>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение теории модуля
 */

export function useGetModuleTheories<TData = Awaited<ReturnType<typeof getModuleTheories>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTheories>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModuleTheoriesQueryOptions(moduleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






