/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptTaskFileRequest,
  AddTaskFileCommentRequest,
  HttpValidationProblemDetails,
  ProblemDetails,
  TaskFileCommentResponse,
  TaskFileResponse,
  UploadStudentTaskFileBody
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getStudentTaskFileResponse200 = {
  data: TaskFileResponse
  status: 200
}

export type getStudentTaskFileResponse401 = {
  data: void
  status: 401
}

export type getStudentTaskFileResponse403 = {
  data: void
  status: 403
}

export type getStudentTaskFileResponse404 = {
  data: void
  status: 404
}

export type getStudentTaskFileResponseSuccess = (getStudentTaskFileResponse200) & {
  headers: Headers;
};
export type getStudentTaskFileResponseError = (getStudentTaskFileResponse401 | getStudentTaskFileResponse403 | getStudentTaskFileResponse404) & {
  headers: Headers;
};

export type getStudentTaskFileResponse = (getStudentTaskFileResponseSuccess | getStudentTaskFileResponseError)

export const getGetStudentTaskFileUrl = (taskId: string,) => {




  return `/api/v1/tasks/${taskId}/file`
}

/**
 * Возвращает файл решения текущего студента по задаче.
 * @summary Получение файла задания студента
 */
export const getStudentTaskFile = async (taskId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getStudentTaskFileResponse> => {

  return educationFetch<getStudentTaskFileResponse>(getGetStudentTaskFileUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentTaskFileQueryKey = (taskId: string,) => {
    return [
    `/api/v1/tasks/${taskId}/file`
    ] as const;
    }


export const getGetStudentTaskFileQueryOptions = <TData = Awaited<ReturnType<typeof getStudentTaskFile>>, TError = void>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskFile>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentTaskFileQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentTaskFile>>> = ({ signal }) => getStudentTaskFile(taskId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentTaskFileQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentTaskFile>>>
export type GetStudentTaskFileQueryError = void


export function useGetStudentTaskFile<TData = Awaited<ReturnType<typeof getStudentTaskFile>>, TError = void>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTaskFile>>,
          TError,
          Awaited<ReturnType<typeof getStudentTaskFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTaskFile<TData = Awaited<ReturnType<typeof getStudentTaskFile>>, TError = void>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTaskFile>>,
          TError,
          Awaited<ReturnType<typeof getStudentTaskFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTaskFile<TData = Awaited<ReturnType<typeof getStudentTaskFile>>, TError = void>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskFile>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение файла задания студента
 */

export function useGetStudentTaskFile<TData = Awaited<ReturnType<typeof getStudentTaskFile>>, TError = void>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskFile>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentTaskFileQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type uploadStudentTaskFileResponse200 = {
  data: TaskFileResponse
  status: 200
}

export type uploadStudentTaskFileResponse400 = {
  data: ProblemDetails
  status: 400
}

export type uploadStudentTaskFileResponse401 = {
  data: void
  status: 401
}

export type uploadStudentTaskFileResponse403 = {
  data: void
  status: 403
}

export type uploadStudentTaskFileResponseSuccess = (uploadStudentTaskFileResponse200) & {
  headers: Headers;
};
export type uploadStudentTaskFileResponseError = (uploadStudentTaskFileResponse400 | uploadStudentTaskFileResponse401 | uploadStudentTaskFileResponse403) & {
  headers: Headers;
};

export type uploadStudentTaskFileResponse = (uploadStudentTaskFileResponseSuccess | uploadStudentTaskFileResponseError)

export const getUploadStudentTaskFileUrl = (taskId: string,) => {




  return `/api/v1/tasks/${taskId}/file`
}

/**
 * Загружает или заменяет файл решения текущего студента по задаче.
 * @summary Загрузка файла задания студентом
 */
export const uploadStudentTaskFile = async (taskId: string,
    uploadStudentTaskFileBody: UploadStudentTaskFileBody, options?: Parameters<typeof educationFetch>[1]): Promise<uploadStudentTaskFileResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadStudentTaskFileBody.file);

  return educationFetch<uploadStudentTaskFileResponse>(getUploadStudentTaskFileUrl(taskId),
  {
    ...options,
    method: 'PUT'
    ,
    body: formData
  }
);}





export const getUploadStudentTaskFileMutationKey = () => ['uploadStudentTaskFile'] as const;

export const getUploadStudentTaskFileMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStudentTaskFile>>, TError,UploadStudentTaskFileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadStudentTaskFile>>, TError,UploadStudentTaskFileMutationVariables, TContext> => {

const mutationKey = getUploadStudentTaskFileMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadStudentTaskFile>>, UploadStudentTaskFileMutationVariables> = (props) => {
          const {taskId,data} = props ?? {};

          return  uploadStudentTaskFile(taskId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadStudentTaskFileMutationResult = NonNullable<Awaited<ReturnType<typeof uploadStudentTaskFile>>>
    export type UploadStudentTaskFileMutationBody = UploadStudentTaskFileBody
    export type UploadStudentTaskFileMutationError = ProblemDetails | void
    export type UploadStudentTaskFileMutationVariables = {taskId: string;data: UploadStudentTaskFileBody}

    /**
 * @summary Загрузка файла задания студентом
 */
export const useUploadStudentTaskFile = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadStudentTaskFile>>, TError,UploadStudentTaskFileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadStudentTaskFile>>,
        TError,
        UploadStudentTaskFileMutationVariables,
        TContext
      > => {
      return useMutation(getUploadStudentTaskFileMutationOptions(options), queryClient);
    }
    export type getTeacherTaskFilesByTaskResponse200 = {
  data: TaskFileResponse[]
  status: 200
}

export type getTeacherTaskFilesByTaskResponse401 = {
  data: void
  status: 401
}

export type getTeacherTaskFilesByTaskResponse403 = {
  data: void
  status: 403
}

export type getTeacherTaskFilesByTaskResponseSuccess = (getTeacherTaskFilesByTaskResponse200) & {
  headers: Headers;
};
export type getTeacherTaskFilesByTaskResponseError = (getTeacherTaskFilesByTaskResponse401 | getTeacherTaskFilesByTaskResponse403) & {
  headers: Headers;
};

export type getTeacherTaskFilesByTaskResponse = (getTeacherTaskFilesByTaskResponseSuccess | getTeacherTaskFilesByTaskResponseError)

export const getGetTeacherTaskFilesByTaskUrl = (taskId: string,) => {




  return `/api/v1/tasks/${taskId}/files`
}

/**
 * Возвращает файлы решений студентов по задаче преподавателя.
 * @summary Получение решений по задаче
 */
export const getTeacherTaskFilesByTask = async (taskId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getTeacherTaskFilesByTaskResponse> => {

  return educationFetch<getTeacherTaskFilesByTaskResponse>(getGetTeacherTaskFilesByTaskUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTeacherTaskFilesByTaskQueryKey = (taskId: string,) => {
    return [
    `/api/v1/tasks/${taskId}/files`
    ] as const;
    }


export const getGetTeacherTaskFilesByTaskQueryOptions = <TData = Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError = void>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeacherTaskFilesByTaskQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>> = ({ signal }) => getTeacherTaskFilesByTask(taskId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTeacherTaskFilesByTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>>
export type GetTeacherTaskFilesByTaskQueryError = void


export function useGetTeacherTaskFilesByTask<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError = void>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>,
          TError,
          Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherTaskFilesByTask<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError = void>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>,
          TError,
          Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherTaskFilesByTask<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError = void>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение решений по задаче
 */

export function useGetTeacherTaskFilesByTask<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError = void>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByTask>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeacherTaskFilesByTaskQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getTeacherTaskFilesByPracticalResponse200 = {
  data: TaskFileResponse[]
  status: 200
}

export type getTeacherTaskFilesByPracticalResponse401 = {
  data: void
  status: 401
}

export type getTeacherTaskFilesByPracticalResponse403 = {
  data: void
  status: 403
}

export type getTeacherTaskFilesByPracticalResponseSuccess = (getTeacherTaskFilesByPracticalResponse200) & {
  headers: Headers;
};
export type getTeacherTaskFilesByPracticalResponseError = (getTeacherTaskFilesByPracticalResponse401 | getTeacherTaskFilesByPracticalResponse403) & {
  headers: Headers;
};

export type getTeacherTaskFilesByPracticalResponse = (getTeacherTaskFilesByPracticalResponseSuccess | getTeacherTaskFilesByPracticalResponseError)

export const getGetTeacherTaskFilesByPracticalUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/task-files`
}

/**
 * Возвращает файлы решений студентов по всем задачам практики преподавателя.
 * @summary Получение решений по практике
 */
export const getTeacherTaskFilesByPractical = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getTeacherTaskFilesByPracticalResponse> => {

  return educationFetch<getTeacherTaskFilesByPracticalResponse>(getGetTeacherTaskFilesByPracticalUrl(practicalId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTeacherTaskFilesByPracticalQueryKey = (practicalId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/task-files`
    ] as const;
    }


export const getGetTeacherTaskFilesByPracticalQueryOptions = <TData = Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError = void>(practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeacherTaskFilesByPracticalQueryKey(practicalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>> = ({ signal }) => getTeacherTaskFilesByPractical(practicalId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTeacherTaskFilesByPracticalQueryResult = NonNullable<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>>
export type GetTeacherTaskFilesByPracticalQueryError = void


export function useGetTeacherTaskFilesByPractical<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError = void>(
 practicalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>,
          TError,
          Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherTaskFilesByPractical<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>,
          TError,
          Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherTaskFilesByPractical<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение решений по практике
 */

export function useGetTeacherTaskFilesByPractical<TData = Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskFilesByPractical>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeacherTaskFilesByPracticalQueryOptions(practicalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type addTaskFileCommentResponse200 = {
  data: TaskFileCommentResponse
  status: 200
}

export type addTaskFileCommentResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type addTaskFileCommentResponse401 = {
  data: void
  status: 401
}

export type addTaskFileCommentResponse403 = {
  data: void
  status: 403
}

export type addTaskFileCommentResponse404 = {
  data: void
  status: 404
}

export type addTaskFileCommentResponseSuccess = (addTaskFileCommentResponse200) & {
  headers: Headers;
};
export type addTaskFileCommentResponseError = (addTaskFileCommentResponse400 | addTaskFileCommentResponse401 | addTaskFileCommentResponse403 | addTaskFileCommentResponse404) & {
  headers: Headers;
};

export type addTaskFileCommentResponse = (addTaskFileCommentResponseSuccess | addTaskFileCommentResponseError)

export const getAddTaskFileCommentUrl = (taskFileId: string,) => {




  return `/api/v1/task-files/${taskFileId}/comments`
}

/**
 * Добавляет комментарий преподавателя к файлу решения студента.
 * @summary Добавление комментария к решению
 */
export const addTaskFileComment = async (taskFileId: string,
    addTaskFileCommentRequest: AddTaskFileCommentRequest, options?: Parameters<typeof educationFetch>[1]): Promise<addTaskFileCommentResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<addTaskFileCommentResponse>(getAddTaskFileCommentUrl(taskFileId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(addTaskFileCommentRequest)
  }
);}





export const getAddTaskFileCommentMutationKey = () => ['addTaskFileComment'] as const;

export const getAddTaskFileCommentMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTaskFileComment>>, TError,AddTaskFileCommentMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addTaskFileComment>>, TError,AddTaskFileCommentMutationVariables, TContext> => {

const mutationKey = getAddTaskFileCommentMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addTaskFileComment>>, AddTaskFileCommentMutationVariables> = (props) => {
          const {taskFileId,data} = props ?? {};

          return  addTaskFileComment(taskFileId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddTaskFileCommentMutationResult = NonNullable<Awaited<ReturnType<typeof addTaskFileComment>>>
    export type AddTaskFileCommentMutationBody = AddTaskFileCommentRequest
    export type AddTaskFileCommentMutationError = HttpValidationProblemDetails | void
    export type AddTaskFileCommentMutationVariables = {taskFileId: string;data: AddTaskFileCommentRequest}

    /**
 * @summary Добавление комментария к решению
 */
export const useAddTaskFileComment = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTaskFileComment>>, TError,AddTaskFileCommentMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addTaskFileComment>>,
        TError,
        AddTaskFileCommentMutationVariables,
        TContext
      > => {
      return useMutation(getAddTaskFileCommentMutationOptions(options), queryClient);
    }
    export type acceptTaskFileResponse204 = {
  data: void
  status: 204
}

export type acceptTaskFileResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type acceptTaskFileResponse401 = {
  data: void
  status: 401
}

export type acceptTaskFileResponse403 = {
  data: void
  status: 403
}

export type acceptTaskFileResponse404 = {
  data: void
  status: 404
}

export type acceptTaskFileResponseSuccess = (acceptTaskFileResponse204) & {
  headers: Headers;
};
export type acceptTaskFileResponseError = (acceptTaskFileResponse400 | acceptTaskFileResponse401 | acceptTaskFileResponse403 | acceptTaskFileResponse404) & {
  headers: Headers;
};

export type acceptTaskFileResponse = (acceptTaskFileResponseSuccess | acceptTaskFileResponseError)

export const getAcceptTaskFileUrl = (taskFileId: string,) => {




  return `/api/v1/task-files/${taskFileId}/accept`
}

/**
 * Фиксирует оценку и статус принятия файла решения студента.
 * @summary Приём решения студента
 */
export const acceptTaskFile = async (taskFileId: string,
    acceptTaskFileRequest: AcceptTaskFileRequest, options?: Parameters<typeof educationFetch>[1]): Promise<acceptTaskFileResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<acceptTaskFileResponse>(getAcceptTaskFileUrl(taskFileId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(acceptTaskFileRequest)
  }
);}





export const getAcceptTaskFileMutationKey = () => ['acceptTaskFile'] as const;

export const getAcceptTaskFileMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptTaskFile>>, TError,AcceptTaskFileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof acceptTaskFile>>, TError,AcceptTaskFileMutationVariables, TContext> => {

const mutationKey = getAcceptTaskFileMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptTaskFile>>, AcceptTaskFileMutationVariables> = (props) => {
          const {taskFileId,data} = props ?? {};

          return  acceptTaskFile(taskFileId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcceptTaskFileMutationResult = NonNullable<Awaited<ReturnType<typeof acceptTaskFile>>>
    export type AcceptTaskFileMutationBody = AcceptTaskFileRequest
    export type AcceptTaskFileMutationError = HttpValidationProblemDetails | void
    export type AcceptTaskFileMutationVariables = {taskFileId: string;data: AcceptTaskFileRequest}

    /**
 * @summary Приём решения студента
 */
export const useAcceptTaskFile = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptTaskFile>>, TError,AcceptTaskFileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof acceptTaskFile>>,
        TError,
        AcceptTaskFileMutationVariables,
        TContext
      > => {
      return useMutation(getAcceptTaskFileMutationOptions(options), queryClient);
    }
