/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePracticalModuleRequest,
  HttpValidationProblemDetails,
  ModuleTaskResponse,
  PracticalModuleResponse,
  UpdatePracticalModuleRequest
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPracticalModulesResponse200 = {
  data: PracticalModuleResponse[]
  status: 200
}

export type getPracticalModulesResponse401 = {
  data: void
  status: 401
}

export type getPracticalModulesResponse403 = {
  data: void
  status: 403
}

export type getPracticalModulesResponseSuccess = (getPracticalModulesResponse200) & {
  headers: Headers;
};
export type getPracticalModulesResponseError = (getPracticalModulesResponse401 | getPracticalModulesResponse403) & {
  headers: Headers;
};

export type getPracticalModulesResponse = (getPracticalModulesResponseSuccess | getPracticalModulesResponseError)

export const getGetPracticalModulesUrl = () => {




  return `/api/v1/admin/practical-modules`
}

/**
 * Возвращает все зарегистрированные внешние практические модули.
 * @summary Получение реестра практических модулей
 */
export const getPracticalModules = async ( options?: Parameters<typeof educationFetch>[1]): Promise<getPracticalModulesResponse> => {

  return educationFetch<getPracticalModulesResponse>(getGetPracticalModulesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticalModulesQueryKey = () => {
    return [
    `/api/v1/admin/practical-modules`
    ] as const;
    }


export const getGetPracticalModulesQueryOptions = <TData = Awaited<ReturnType<typeof getPracticalModules>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModules>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticalModulesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticalModules>>> = ({ signal }) => getPracticalModules({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticalModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPracticalModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticalModules>>>
export type GetPracticalModulesQueryError = void


export function useGetPracticalModules<TData = Awaited<ReturnType<typeof getPracticalModules>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalModules>>,
          TError,
          Awaited<ReturnType<typeof getPracticalModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalModules<TData = Awaited<ReturnType<typeof getPracticalModules>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalModules>>,
          TError,
          Awaited<ReturnType<typeof getPracticalModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalModules<TData = Awaited<ReturnType<typeof getPracticalModules>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModules>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение реестра практических модулей
 */

export function useGetPracticalModules<TData = Awaited<ReturnType<typeof getPracticalModules>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModules>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPracticalModulesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createPracticalModuleResponse201 = {
  data: PracticalModuleResponse
  status: 201
}

export type createPracticalModuleResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createPracticalModuleResponse401 = {
  data: void
  status: 401
}

export type createPracticalModuleResponse403 = {
  data: void
  status: 403
}

export type createPracticalModuleResponse409 = {
  data: void
  status: 409
}

export type createPracticalModuleResponseSuccess = (createPracticalModuleResponse201) & {
  headers: Headers;
};
export type createPracticalModuleResponseError = (createPracticalModuleResponse400 | createPracticalModuleResponse401 | createPracticalModuleResponse403 | createPracticalModuleResponse409) & {
  headers: Headers;
};

export type createPracticalModuleResponse = (createPracticalModuleResponseSuccess | createPracticalModuleResponseError)

export const getCreatePracticalModuleUrl = () => {




  return `/api/v1/admin/practical-modules`
}

/**
 * Добавляет новую запись в реестр внешних практических модулей.
 * @summary Регистрация практического модуля
 */
export const createPracticalModule = async (createPracticalModuleRequest: CreatePracticalModuleRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createPracticalModuleResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createPracticalModuleResponse>(getCreatePracticalModuleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createPracticalModuleRequest)
  }
);}





export const getCreatePracticalModuleMutationKey = () => ['createPracticalModule'] as const;

export const getCreatePracticalModuleMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPracticalModule>>, TError,CreatePracticalModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPracticalModule>>, TError,CreatePracticalModuleMutationVariables, TContext> => {

const mutationKey = getCreatePracticalModuleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPracticalModule>>, CreatePracticalModuleMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createPracticalModule(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePracticalModuleMutationResult = NonNullable<Awaited<ReturnType<typeof createPracticalModule>>>
    export type CreatePracticalModuleMutationBody = CreatePracticalModuleRequest
    export type CreatePracticalModuleMutationError = HttpValidationProblemDetails | void
    export type CreatePracticalModuleMutationVariables = {data: CreatePracticalModuleRequest}

    /**
 * @summary Регистрация практического модуля
 */
export const useCreatePracticalModule = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPracticalModule>>, TError,CreatePracticalModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPracticalModule>>,
        TError,
        CreatePracticalModuleMutationVariables,
        TContext
      > => {
      return useMutation(getCreatePracticalModuleMutationOptions(options), queryClient);
    }
    export type updatePracticalModuleResponse200 = {
  data: PracticalModuleResponse
  status: 200
}

export type updatePracticalModuleResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updatePracticalModuleResponse401 = {
  data: void
  status: 401
}

export type updatePracticalModuleResponse403 = {
  data: void
  status: 403
}

export type updatePracticalModuleResponse404 = {
  data: void
  status: 404
}

export type updatePracticalModuleResponseSuccess = (updatePracticalModuleResponse200) & {
  headers: Headers;
};
export type updatePracticalModuleResponseError = (updatePracticalModuleResponse400 | updatePracticalModuleResponse401 | updatePracticalModuleResponse403 | updatePracticalModuleResponse404) & {
  headers: Headers;
};

export type updatePracticalModuleResponse = (updatePracticalModuleResponseSuccess | updatePracticalModuleResponseError)

export const getUpdatePracticalModuleUrl = (id: string,) => {




  return `/api/v1/admin/practical-modules/${id}`
}

/**
 * Обновляет запись реестра практического модуля. Slug не меняется.
 * @summary Изменение практического модуля
 */
export const updatePracticalModule = async (id: string,
    updatePracticalModuleRequest: UpdatePracticalModuleRequest, options?: Parameters<typeof educationFetch>[1]): Promise<updatePracticalModuleResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<updatePracticalModuleResponse>(getUpdatePracticalModuleUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updatePracticalModuleRequest)
  }
);}





export const getUpdatePracticalModuleMutationKey = () => ['updatePracticalModule'] as const;

export const getUpdatePracticalModuleMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePracticalModule>>, TError,UpdatePracticalModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePracticalModule>>, TError,UpdatePracticalModuleMutationVariables, TContext> => {

const mutationKey = getUpdatePracticalModuleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePracticalModule>>, UpdatePracticalModuleMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updatePracticalModule(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePracticalModuleMutationResult = NonNullable<Awaited<ReturnType<typeof updatePracticalModule>>>
    export type UpdatePracticalModuleMutationBody = UpdatePracticalModuleRequest
    export type UpdatePracticalModuleMutationError = HttpValidationProblemDetails | void
    export type UpdatePracticalModuleMutationVariables = {id: string;data: UpdatePracticalModuleRequest}

    /**
 * @summary Изменение практического модуля
 */
export const useUpdatePracticalModule = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePracticalModule>>, TError,UpdatePracticalModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePracticalModule>>,
        TError,
        UpdatePracticalModuleMutationVariables,
        TContext
      > => {
      return useMutation(getUpdatePracticalModuleMutationOptions(options), queryClient);
    }
    export type deletePracticalModuleResponse204 = {
  data: void
  status: 204
}

export type deletePracticalModuleResponse401 = {
  data: void
  status: 401
}

export type deletePracticalModuleResponse403 = {
  data: void
  status: 403
}

export type deletePracticalModuleResponse404 = {
  data: void
  status: 404
}

export type deletePracticalModuleResponseSuccess = (deletePracticalModuleResponse204) & {
  headers: Headers;
};
export type deletePracticalModuleResponseError = (deletePracticalModuleResponse401 | deletePracticalModuleResponse403 | deletePracticalModuleResponse404) & {
  headers: Headers;
};

export type deletePracticalModuleResponse = (deletePracticalModuleResponseSuccess | deletePracticalModuleResponseError)

export const getDeletePracticalModuleUrl = (id: string,) => {




  return `/api/v1/admin/practical-modules/${id}`
}

/**
 * Удаляет запись реестра практического модуля.
 * @summary Удаление практического модуля
 */
export const deletePracticalModule = async (id: string, options?: Parameters<typeof educationFetch>[1]): Promise<deletePracticalModuleResponse> => {

  return educationFetch<deletePracticalModuleResponse>(getDeletePracticalModuleUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePracticalModuleMutationKey = () => ['deletePracticalModule'] as const;

export const getDeletePracticalModuleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePracticalModule>>, TError,DeletePracticalModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePracticalModule>>, TError,DeletePracticalModuleMutationVariables, TContext> => {

const mutationKey = getDeletePracticalModuleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePracticalModule>>, DeletePracticalModuleMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deletePracticalModule(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePracticalModuleMutationResult = NonNullable<Awaited<ReturnType<typeof deletePracticalModule>>>

    export type DeletePracticalModuleMutationError = void
    export type DeletePracticalModuleMutationVariables = {id: string}

    /**
 * @summary Удаление практического модуля
 */
export const useDeletePracticalModule = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePracticalModule>>, TError,DeletePracticalModuleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePracticalModule>>,
        TError,
        DeletePracticalModuleMutationVariables,
        TContext
      > => {
      return useMutation(getDeletePracticalModuleMutationOptions(options), queryClient);
    }
    export type getPracticalModuleTasksResponse200 = {
  data: ModuleTaskResponse[]
  status: 200
}

export type getPracticalModuleTasksResponse401 = {
  data: void
  status: 401
}

export type getPracticalModuleTasksResponse403 = {
  data: void
  status: 403
}

export type getPracticalModuleTasksResponse404 = {
  data: void
  status: 404
}

export type getPracticalModuleTasksResponse502 = {
  data: void
  status: 502
}

export type getPracticalModuleTasksResponseSuccess = (getPracticalModuleTasksResponse200) & {
  headers: Headers;
};
export type getPracticalModuleTasksResponseError = (getPracticalModuleTasksResponse401 | getPracticalModuleTasksResponse403 | getPracticalModuleTasksResponse404 | getPracticalModuleTasksResponse502) & {
  headers: Headers;
};

export type getPracticalModuleTasksResponse = (getPracticalModuleTasksResponseSuccess | getPracticalModuleTasksResponseError)

export const getGetPracticalModuleTasksUrl = (practicalModuleId: string,) => {




  return `/api/v1/practical-modules/${practicalModuleId}/tasks`
}

/**
 * Сервер-сервер: ядро проксирует ручку каталога модуля. Браузер к API модуля не ходит.
 * @summary Каталог заданий внешнего модуля
 */
export const getPracticalModuleTasks = async (practicalModuleId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getPracticalModuleTasksResponse> => {

  return educationFetch<getPracticalModuleTasksResponse>(getGetPracticalModuleTasksUrl(practicalModuleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticalModuleTasksQueryKey = (practicalModuleId: string,) => {
    return [
    `/api/v1/practical-modules/${practicalModuleId}/tasks`
    ] as const;
    }


export const getGetPracticalModuleTasksQueryOptions = <TData = Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError = void>(practicalModuleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticalModuleTasksQueryKey(practicalModuleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticalModuleTasks>>> = ({ signal }) => getPracticalModuleTasks(practicalModuleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalModuleId !== null && practicalModuleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPracticalModuleTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticalModuleTasks>>>
export type GetPracticalModuleTasksQueryError = void


export function useGetPracticalModuleTasks<TData = Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError = void>(
 practicalModuleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalModuleTasks>>,
          TError,
          Awaited<ReturnType<typeof getPracticalModuleTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalModuleTasks<TData = Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError = void>(
 practicalModuleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalModuleTasks>>,
          TError,
          Awaited<ReturnType<typeof getPracticalModuleTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalModuleTasks<TData = Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError = void>(
 practicalModuleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Каталог заданий внешнего модуля
 */

export function useGetPracticalModuleTasks<TData = Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError = void>(
 practicalModuleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalModuleTasks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPracticalModuleTasksQueryOptions(practicalModuleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






