/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiV1AdminPingResponse200 = {
  data: void
  status: 200
}

export type getApiV1AdminPingResponse401 = {
  data: void
  status: 401
}

export type getApiV1AdminPingResponse403 = {
  data: void
  status: 403
}

export type getApiV1AdminPingResponseSuccess = (getApiV1AdminPingResponse200) & {
  headers: Headers;
};
export type getApiV1AdminPingResponseError = (getApiV1AdminPingResponse401 | getApiV1AdminPingResponse403) & {
  headers: Headers;
};

export type getApiV1AdminPingResponse = (getApiV1AdminPingResponseSuccess | getApiV1AdminPingResponseError)

export const getGetApiV1AdminPingUrl = () => {




  return `/api/v1/admin/ping`
}

/**
 * Проверяет, что Bearer-токен содержит роль Admin.
 * @summary Проверка доступа администратора
 */
export const getApiV1AdminPing = async ( options?: Parameters<typeof educationFetch>[1]): Promise<getApiV1AdminPingResponse> => {

  return educationFetch<getApiV1AdminPingResponse>(getGetApiV1AdminPingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AdminPingQueryKey = () => {
    return [
    `/api/v1/admin/ping`
    ] as const;
    }


export const getGetApiV1AdminPingQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminPing>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminPingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminPing>>> = ({ signal }) => getApiV1AdminPing({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminPingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminPing>>>
export type GetApiV1AdminPingQueryError = void


export function useGetApiV1AdminPing<TData = Awaited<ReturnType<typeof getApiV1AdminPing>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminPing>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminPing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminPing<TData = Awaited<ReturnType<typeof getApiV1AdminPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminPing>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminPing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminPing<TData = Awaited<ReturnType<typeof getApiV1AdminPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Проверка доступа администратора
 */

export function useGetApiV1AdminPing<TData = Awaited<ReturnType<typeof getApiV1AdminPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminPingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






