/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminProfileResponse,
  AssignableStudentResponse,
  ChangeStudentsRequest,
  CreateAdminProfileRequest,
  GetCourseStudentAssignmentsParams,
  GetPracticalStudentAssignmentsParams,
  HttpValidationProblemDetails,
  ProblemDetails,
  StudentAssignmentPageResponse,
  UpdateAdminProfileRequest,
  UpdateCourseStudentsRequest,
  UpdatePracticalStudentsRequest
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getAdminProfilesResponse200 = {
  data: AdminProfileResponse[]
  status: 200
}

export type getAdminProfilesResponse401 = {
  data: void
  status: 401
}

export type getAdminProfilesResponse403 = {
  data: void
  status: 403
}

export type getAdminProfilesResponseSuccess = (getAdminProfilesResponse200) & {
  headers: Headers;
};
export type getAdminProfilesResponseError = (getAdminProfilesResponse401 | getAdminProfilesResponse403) & {
  headers: Headers;
};

export type getAdminProfilesResponse = (getAdminProfilesResponseSuccess | getAdminProfilesResponseError)

export const getGetAdminProfilesUrl = () => {




  return `/api/v1/admin/profiles`
}

/**
 * Возвращает связанные профили пользователей для администрирования.
 * @summary Получение профилей пользователей
 */
export const getAdminProfiles = async ( options?: Parameters<typeof educationFetch>[1]): Promise<getAdminProfilesResponse> => {

  return educationFetch<getAdminProfilesResponse>(getGetAdminProfilesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminProfilesQueryKey = () => {
    return [
    `/api/v1/admin/profiles`
    ] as const;
    }


export const getGetAdminProfilesQueryOptions = <TData = Awaited<ReturnType<typeof getAdminProfiles>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfiles>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminProfilesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminProfiles>>> = ({ signal }) => getAdminProfiles({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminProfiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminProfilesQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminProfiles>>>
export type GetAdminProfilesQueryError = void


export function useGetAdminProfiles<TData = Awaited<ReturnType<typeof getAdminProfiles>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminProfiles>>,
          TError,
          Awaited<ReturnType<typeof getAdminProfiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminProfiles<TData = Awaited<ReturnType<typeof getAdminProfiles>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminProfiles>>,
          TError,
          Awaited<ReturnType<typeof getAdminProfiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminProfiles<TData = Awaited<ReturnType<typeof getAdminProfiles>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfiles>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение профилей пользователей
 */

export function useGetAdminProfiles<TData = Awaited<ReturnType<typeof getAdminProfiles>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProfiles>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminProfilesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createAdminProfileResponse201 = {
  data: AdminProfileResponse
  status: 201
}

export type createAdminProfileResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createAdminProfileResponse401 = {
  data: void
  status: 401
}

export type createAdminProfileResponse403 = {
  data: void
  status: 403
}

export type createAdminProfileResponse409 = {
  data: void
  status: 409
}

export type createAdminProfileResponseSuccess = (createAdminProfileResponse201) & {
  headers: Headers;
};
export type createAdminProfileResponseError = (createAdminProfileResponse400 | createAdminProfileResponse401 | createAdminProfileResponse403 | createAdminProfileResponse409) & {
  headers: Headers;
};

export type createAdminProfileResponse = (createAdminProfileResponseSuccess | createAdminProfileResponseError)

export const getCreateAdminProfileUrl = () => {




  return `/api/v1/admin/profiles`
}

/**
 * Создаёт legacy-профиль пользователя и связывает его с identity-пользователем.
 * @summary Создание связанного профиля
 */
export const createAdminProfile = async (createAdminProfileRequest: CreateAdminProfileRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createAdminProfileResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createAdminProfileResponse>(getCreateAdminProfileUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createAdminProfileRequest)
  }
);}





export const getCreateAdminProfileMutationKey = () => ['createAdminProfile'] as const;

export const getCreateAdminProfileMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminProfile>>, TError,CreateAdminProfileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminProfile>>, TError,CreateAdminProfileMutationVariables, TContext> => {

const mutationKey = getCreateAdminProfileMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminProfile>>, CreateAdminProfileMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createAdminProfile(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminProfileMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminProfile>>>
    export type CreateAdminProfileMutationBody = CreateAdminProfileRequest
    export type CreateAdminProfileMutationError = HttpValidationProblemDetails | void
    export type CreateAdminProfileMutationVariables = {data: CreateAdminProfileRequest}

    /**
 * @summary Создание связанного профиля
 */
export const useCreateAdminProfile = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminProfile>>, TError,CreateAdminProfileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAdminProfile>>,
        TError,
        CreateAdminProfileMutationVariables,
        TContext
      > => {
      return useMutation(getCreateAdminProfileMutationOptions(options), queryClient);
    }
    export type updateAdminProfileResponse200 = {
  data: AdminProfileResponse
  status: 200
}

export type updateAdminProfileResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateAdminProfileResponse401 = {
  data: void
  status: 401
}

export type updateAdminProfileResponse403 = {
  data: void
  status: 403
}

export type updateAdminProfileResponse404 = {
  data: void
  status: 404
}

export type updateAdminProfileResponseSuccess = (updateAdminProfileResponse200) & {
  headers: Headers;
};
export type updateAdminProfileResponseError = (updateAdminProfileResponse400 | updateAdminProfileResponse401 | updateAdminProfileResponse403 | updateAdminProfileResponse404) & {
  headers: Headers;
};

export type updateAdminProfileResponse = (updateAdminProfileResponseSuccess | updateAdminProfileResponseError)

export const getUpdateAdminProfileUrl = (legacyUserId: string,) => {




  return `/api/v1/admin/profiles/${legacyUserId}`
}

/**
 * Обновляет данные legacy-профиля пользователя.
 * @summary Обновление профиля пользователя
 */
export const updateAdminProfile = async (legacyUserId: string,
    updateAdminProfileRequest: UpdateAdminProfileRequest, options?: Parameters<typeof educationFetch>[1]): Promise<updateAdminProfileResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<updateAdminProfileResponse>(getUpdateAdminProfileUrl(legacyUserId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateAdminProfileRequest)
  }
);}





export const getUpdateAdminProfileMutationKey = () => ['updateAdminProfile'] as const;

export const getUpdateAdminProfileMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminProfile>>, TError,UpdateAdminProfileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminProfile>>, TError,UpdateAdminProfileMutationVariables, TContext> => {

const mutationKey = getUpdateAdminProfileMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminProfile>>, UpdateAdminProfileMutationVariables> = (props) => {
          const {legacyUserId,data} = props ?? {};

          return  updateAdminProfile(legacyUserId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminProfile>>>
    export type UpdateAdminProfileMutationBody = UpdateAdminProfileRequest
    export type UpdateAdminProfileMutationError = HttpValidationProblemDetails | void
    export type UpdateAdminProfileMutationVariables = {legacyUserId: string;data: UpdateAdminProfileRequest}

    /**
 * @summary Обновление профиля пользователя
 */
export const useUpdateAdminProfile = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminProfile>>, TError,UpdateAdminProfileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminProfile>>,
        TError,
        UpdateAdminProfileMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateAdminProfileMutationOptions(options), queryClient);
    }
    export type deactivateAdminProfileResponse204 = {
  data: void
  status: 204
}

export type deactivateAdminProfileResponse401 = {
  data: void
  status: 401
}

export type deactivateAdminProfileResponse403 = {
  data: void
  status: 403
}

export type deactivateAdminProfileResponse404 = {
  data: void
  status: 404
}

export type deactivateAdminProfileResponseSuccess = (deactivateAdminProfileResponse204) & {
  headers: Headers;
};
export type deactivateAdminProfileResponseError = (deactivateAdminProfileResponse401 | deactivateAdminProfileResponse403 | deactivateAdminProfileResponse404) & {
  headers: Headers;
};

export type deactivateAdminProfileResponse = (deactivateAdminProfileResponseSuccess | deactivateAdminProfileResponseError)

export const getDeactivateAdminProfileUrl = (legacyUserId: string,) => {




  return `/api/v1/admin/profiles/${legacyUserId}/deactivate`
}

/**
 * Отключает связь legacy-профиля с identity-пользователем.
 * @summary Деактивация связи профиля
 */
export const deactivateAdminProfile = async (legacyUserId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deactivateAdminProfileResponse> => {

  return educationFetch<deactivateAdminProfileResponse>(getDeactivateAdminProfileUrl(legacyUserId),
  {
    ...options,
    method: 'PUT'


  }
);}





export const getDeactivateAdminProfileMutationKey = () => ['deactivateAdminProfile'] as const;

export const getDeactivateAdminProfileMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateAdminProfile>>, TError,DeactivateAdminProfileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateAdminProfile>>, TError,DeactivateAdminProfileMutationVariables, TContext> => {

const mutationKey = getDeactivateAdminProfileMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateAdminProfile>>, DeactivateAdminProfileMutationVariables> = (props) => {
          const {legacyUserId} = props ?? {};

          return  deactivateAdminProfile(legacyUserId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeactivateAdminProfileMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateAdminProfile>>>

    export type DeactivateAdminProfileMutationError = void
    export type DeactivateAdminProfileMutationVariables = {legacyUserId: string}

    /**
 * @summary Деактивация связи профиля
 */
export const useDeactivateAdminProfile = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateAdminProfile>>, TError,DeactivateAdminProfileMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateAdminProfile>>,
        TError,
        DeactivateAdminProfileMutationVariables,
        TContext
      > => {
      return useMutation(getDeactivateAdminProfileMutationOptions(options), queryClient);
    }
    export type getCourseAssignableStudentsResponse200 = {
  data: AssignableStudentResponse[]
  status: 200
}

export type getCourseAssignableStudentsResponse401 = {
  data: void
  status: 401
}

export type getCourseAssignableStudentsResponse403 = {
  data: void
  status: 403
}

export type getCourseAssignableStudentsResponseSuccess = (getCourseAssignableStudentsResponse200) & {
  headers: Headers;
};
export type getCourseAssignableStudentsResponseError = (getCourseAssignableStudentsResponse401 | getCourseAssignableStudentsResponse403) & {
  headers: Headers;
};

export type getCourseAssignableStudentsResponse = (getCourseAssignableStudentsResponseSuccess | getCourseAssignableStudentsResponseError)

export const getGetCourseAssignableStudentsUrl = (courseId: string,) => {




  return `/api/v1/courses/${courseId}/assignable-students`
}

/**
 * Студенты с признаком назначения на выбранный курс. Только для преподавателя-владельца курса.
 * @summary Получение студентов для назначения на курс
 */
export const getCourseAssignableStudents = async (courseId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getCourseAssignableStudentsResponse> => {

  return educationFetch<getCourseAssignableStudentsResponse>(getGetCourseAssignableStudentsUrl(courseId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCourseAssignableStudentsQueryKey = (courseId: string,) => {
    return [
    `/api/v1/courses/${courseId}/assignable-students`
    ] as const;
    }


export const getGetCourseAssignableStudentsQueryOptions = <TData = Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError = void>(courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCourseAssignableStudentsQueryKey(courseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourseAssignableStudents>>> = ({ signal }) => getCourseAssignableStudents(courseId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: courseId !== null && courseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCourseAssignableStudentsQueryResult = NonNullable<Awaited<ReturnType<typeof getCourseAssignableStudents>>>
export type GetCourseAssignableStudentsQueryError = void


export function useGetCourseAssignableStudents<TData = Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError = void>(
 courseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourseAssignableStudents>>,
          TError,
          Awaited<ReturnType<typeof getCourseAssignableStudents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourseAssignableStudents<TData = Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError = void>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourseAssignableStudents>>,
          TError,
          Awaited<ReturnType<typeof getCourseAssignableStudents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourseAssignableStudents<TData = Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError = void>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение студентов для назначения на курс
 */

export function useGetCourseAssignableStudents<TData = Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError = void>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseAssignableStudents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCourseAssignableStudentsQueryOptions(courseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getPracticalAssignableStudentsResponse200 = {
  data: AssignableStudentResponse[]
  status: 200
}

export type getPracticalAssignableStudentsResponse401 = {
  data: void
  status: 401
}

export type getPracticalAssignableStudentsResponse403 = {
  data: void
  status: 403
}

export type getPracticalAssignableStudentsResponseSuccess = (getPracticalAssignableStudentsResponse200) & {
  headers: Headers;
};
export type getPracticalAssignableStudentsResponseError = (getPracticalAssignableStudentsResponse401 | getPracticalAssignableStudentsResponse403) & {
  headers: Headers;
};

export type getPracticalAssignableStudentsResponse = (getPracticalAssignableStudentsResponseSuccess | getPracticalAssignableStudentsResponseError)

export const getGetPracticalAssignableStudentsUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/assignable-students`
}

/**
 * Студенты с признаком назначения на выбранную практику. Только для преподавателя-владельца практики.
 * @summary Получение студентов для назначения на практику
 */
export const getPracticalAssignableStudents = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getPracticalAssignableStudentsResponse> => {

  return educationFetch<getPracticalAssignableStudentsResponse>(getGetPracticalAssignableStudentsUrl(practicalId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticalAssignableStudentsQueryKey = (practicalId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/assignable-students`
    ] as const;
    }


export const getGetPracticalAssignableStudentsQueryOptions = <TData = Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError = void>(practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticalAssignableStudentsQueryKey(practicalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticalAssignableStudents>>> = ({ signal }) => getPracticalAssignableStudents(practicalId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPracticalAssignableStudentsQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticalAssignableStudents>>>
export type GetPracticalAssignableStudentsQueryError = void


export function useGetPracticalAssignableStudents<TData = Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError = void>(
 practicalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalAssignableStudents>>,
          TError,
          Awaited<ReturnType<typeof getPracticalAssignableStudents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalAssignableStudents<TData = Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalAssignableStudents>>,
          TError,
          Awaited<ReturnType<typeof getPracticalAssignableStudents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalAssignableStudents<TData = Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение студентов для назначения на практику
 */

export function useGetPracticalAssignableStudents<TData = Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalAssignableStudents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPracticalAssignableStudentsQueryOptions(practicalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type setCourseStudentsResponse204 = {
  data: void
  status: 204
}

export type setCourseStudentsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type setCourseStudentsResponse401 = {
  data: void
  status: 401
}

export type setCourseStudentsResponse403 = {
  data: void
  status: 403
}

export type setCourseStudentsResponseSuccess = (setCourseStudentsResponse204) & {
  headers: Headers;
};
export type setCourseStudentsResponseError = (setCourseStudentsResponse400 | setCourseStudentsResponse401 | setCourseStudentsResponse403) & {
  headers: Headers;
};

export type setCourseStudentsResponse = (setCourseStudentsResponseSuccess | setCourseStudentsResponseError)

export const getSetCourseStudentsUrl = (courseId: string,) => {




  return `/api/v1/courses/${courseId}/students`
}

/**
 * Заменяет набор студентов курса. Только для преподавателя-владельца; неизвестные / не привязанные id → 400.
 * @summary Назначение студентов на курс
 */
export const setCourseStudents = async (courseId: string,
    updateCourseStudentsRequest: UpdateCourseStudentsRequest, options?: Parameters<typeof educationFetch>[1]): Promise<setCourseStudentsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<setCourseStudentsResponse>(getSetCourseStudentsUrl(courseId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateCourseStudentsRequest)
  }
);}





export const getSetCourseStudentsMutationKey = () => ['setCourseStudents'] as const;

export const getSetCourseStudentsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setCourseStudents>>, TError,SetCourseStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setCourseStudents>>, TError,SetCourseStudentsMutationVariables, TContext> => {

const mutationKey = getSetCourseStudentsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setCourseStudents>>, SetCourseStudentsMutationVariables> = (props) => {
          const {courseId,data} = props ?? {};

          return  setCourseStudents(courseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetCourseStudentsMutationResult = NonNullable<Awaited<ReturnType<typeof setCourseStudents>>>
    export type SetCourseStudentsMutationBody = UpdateCourseStudentsRequest
    export type SetCourseStudentsMutationError = ProblemDetails | void
    export type SetCourseStudentsMutationVariables = {courseId: string;data: UpdateCourseStudentsRequest}

    /**
 * @summary Назначение студентов на курс
 */
export const useSetCourseStudents = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setCourseStudents>>, TError,SetCourseStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setCourseStudents>>,
        TError,
        SetCourseStudentsMutationVariables,
        TContext
      > => {
      return useMutation(getSetCourseStudentsMutationOptions(options), queryClient);
    }
    export type setPracticalStudentsResponse204 = {
  data: void
  status: 204
}

export type setPracticalStudentsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type setPracticalStudentsResponse401 = {
  data: void
  status: 401
}

export type setPracticalStudentsResponse403 = {
  data: void
  status: 403
}

export type setPracticalStudentsResponseSuccess = (setPracticalStudentsResponse204) & {
  headers: Headers;
};
export type setPracticalStudentsResponseError = (setPracticalStudentsResponse400 | setPracticalStudentsResponse401 | setPracticalStudentsResponse403) & {
  headers: Headers;
};

export type setPracticalStudentsResponse = (setPracticalStudentsResponseSuccess | setPracticalStudentsResponseError)

export const getSetPracticalStudentsUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/students`
}

/**
 * Заменяет набор студентов практики. Только для преподавателя-владельца; неизвестные / не привязанные id → 400.
 * @summary Назначение студентов на практику
 */
export const setPracticalStudents = async (practicalId: string,
    updatePracticalStudentsRequest: UpdatePracticalStudentsRequest, options?: Parameters<typeof educationFetch>[1]): Promise<setPracticalStudentsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<setPracticalStudentsResponse>(getSetPracticalStudentsUrl(practicalId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updatePracticalStudentsRequest)
  }
);}





export const getSetPracticalStudentsMutationKey = () => ['setPracticalStudents'] as const;

export const getSetPracticalStudentsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setPracticalStudents>>, TError,SetPracticalStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setPracticalStudents>>, TError,SetPracticalStudentsMutationVariables, TContext> => {

const mutationKey = getSetPracticalStudentsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setPracticalStudents>>, SetPracticalStudentsMutationVariables> = (props) => {
          const {practicalId,data} = props ?? {};

          return  setPracticalStudents(practicalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetPracticalStudentsMutationResult = NonNullable<Awaited<ReturnType<typeof setPracticalStudents>>>
    export type SetPracticalStudentsMutationBody = UpdatePracticalStudentsRequest
    export type SetPracticalStudentsMutationError = ProblemDetails | void
    export type SetPracticalStudentsMutationVariables = {practicalId: string;data: UpdatePracticalStudentsRequest}

    /**
 * @summary Назначение студентов на практику
 */
export const useSetPracticalStudents = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setPracticalStudents>>, TError,SetPracticalStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setPracticalStudents>>,
        TError,
        SetPracticalStudentsMutationVariables,
        TContext
      > => {
      return useMutation(getSetPracticalStudentsMutationOptions(options), queryClient);
    }
    export type getCourseStudentAssignmentsResponse200 = {
  data: StudentAssignmentPageResponse
  status: 200
}

export type getCourseStudentAssignmentsResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getCourseStudentAssignmentsResponse401 = {
  data: void
  status: 401
}

export type getCourseStudentAssignmentsResponse403 = {
  data: void
  status: 403
}

export type getCourseStudentAssignmentsResponseSuccess = (getCourseStudentAssignmentsResponse200) & {
  headers: Headers;
};
export type getCourseStudentAssignmentsResponseError = (getCourseStudentAssignmentsResponse400 | getCourseStudentAssignmentsResponse401 | getCourseStudentAssignmentsResponse403) & {
  headers: Headers;
};

export type getCourseStudentAssignmentsResponse = (getCourseStudentAssignmentsResponseSuccess | getCourseStudentAssignmentsResponseError)

export const getGetCourseStudentAssignmentsUrl = (courseId: string,
    params?: GetCourseStudentAssignmentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/courses/${courseId}/student-assignments?${stringifiedParams}` : `/api/v1/courses/${courseId}/student-assignments`
}

/**
 * Поиск по ФИО и логину, фильтр assigned (true/false), страницы по pageSize ≤ 200. Только для преподавателя-владельца курса.
 * @summary Постраничный список студентов для назначения на курс
 */
export const getCourseStudentAssignments = async (courseId: string,
    params?: GetCourseStudentAssignmentsParams, options?: Parameters<typeof educationFetch>[1]): Promise<getCourseStudentAssignmentsResponse> => {

  return educationFetch<getCourseStudentAssignmentsResponse>(getGetCourseStudentAssignmentsUrl(courseId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCourseStudentAssignmentsQueryKey = (courseId: string,
    params?: GetCourseStudentAssignmentsParams,) => {
    return [
    `/api/v1/courses/${courseId}/student-assignments`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCourseStudentAssignmentsQueryOptions = <TData = Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError = HttpValidationProblemDetails | void>(courseId: string,
    params?: GetCourseStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCourseStudentAssignmentsQueryKey(courseId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourseStudentAssignments>>> = ({ signal }) => getCourseStudentAssignments(courseId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: courseId !== null && courseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCourseStudentAssignmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getCourseStudentAssignments>>>
export type GetCourseStudentAssignmentsQueryError = HttpValidationProblemDetails | void


export function useGetCourseStudentAssignments<TData = Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 courseId: string,
    params: undefined |  GetCourseStudentAssignmentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourseStudentAssignments>>,
          TError,
          Awaited<ReturnType<typeof getCourseStudentAssignments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourseStudentAssignments<TData = Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 courseId: string,
    params?: GetCourseStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourseStudentAssignments>>,
          TError,
          Awaited<ReturnType<typeof getCourseStudentAssignments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourseStudentAssignments<TData = Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 courseId: string,
    params?: GetCourseStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Постраничный список студентов для назначения на курс
 */

export function useGetCourseStudentAssignments<TData = Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 courseId: string,
    params?: GetCourseStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseStudentAssignments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCourseStudentAssignmentsQueryOptions(courseId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getPracticalStudentAssignmentsResponse200 = {
  data: StudentAssignmentPageResponse
  status: 200
}

export type getPracticalStudentAssignmentsResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getPracticalStudentAssignmentsResponse401 = {
  data: void
  status: 401
}

export type getPracticalStudentAssignmentsResponse403 = {
  data: void
  status: 403
}

export type getPracticalStudentAssignmentsResponseSuccess = (getPracticalStudentAssignmentsResponse200) & {
  headers: Headers;
};
export type getPracticalStudentAssignmentsResponseError = (getPracticalStudentAssignmentsResponse400 | getPracticalStudentAssignmentsResponse401 | getPracticalStudentAssignmentsResponse403) & {
  headers: Headers;
};

export type getPracticalStudentAssignmentsResponse = (getPracticalStudentAssignmentsResponseSuccess | getPracticalStudentAssignmentsResponseError)

export const getGetPracticalStudentAssignmentsUrl = (practicalId: string,
    params?: GetPracticalStudentAssignmentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/practicals/${practicalId}/student-assignments?${stringifiedParams}` : `/api/v1/practicals/${practicalId}/student-assignments`
}

/**
 * Поиск по ФИО и логину, фильтр assigned (true/false), страницы по pageSize ≤ 200. Только для преподавателя-владельца практики.
 * @summary Постраничный список студентов для назначения на практику
 */
export const getPracticalStudentAssignments = async (practicalId: string,
    params?: GetPracticalStudentAssignmentsParams, options?: Parameters<typeof educationFetch>[1]): Promise<getPracticalStudentAssignmentsResponse> => {

  return educationFetch<getPracticalStudentAssignmentsResponse>(getGetPracticalStudentAssignmentsUrl(practicalId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticalStudentAssignmentsQueryKey = (practicalId: string,
    params?: GetPracticalStudentAssignmentsParams,) => {
    return [
    `/api/v1/practicals/${practicalId}/student-assignments`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPracticalStudentAssignmentsQueryOptions = <TData = Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError = HttpValidationProblemDetails | void>(practicalId: string,
    params?: GetPracticalStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticalStudentAssignmentsQueryKey(practicalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticalStudentAssignments>>> = ({ signal }) => getPracticalStudentAssignments(practicalId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPracticalStudentAssignmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticalStudentAssignments>>>
export type GetPracticalStudentAssignmentsQueryError = HttpValidationProblemDetails | void


export function useGetPracticalStudentAssignments<TData = Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 practicalId: string,
    params: undefined |  GetPracticalStudentAssignmentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalStudentAssignments>>,
          TError,
          Awaited<ReturnType<typeof getPracticalStudentAssignments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalStudentAssignments<TData = Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 practicalId: string,
    params?: GetPracticalStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalStudentAssignments>>,
          TError,
          Awaited<ReturnType<typeof getPracticalStudentAssignments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalStudentAssignments<TData = Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 practicalId: string,
    params?: GetPracticalStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Постраничный список студентов для назначения на практику
 */

export function useGetPracticalStudentAssignments<TData = Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError = HttpValidationProblemDetails | void>(
 practicalId: string,
    params?: GetPracticalStudentAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalStudentAssignments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPracticalStudentAssignmentsQueryOptions(practicalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type changeCourseStudentsResponse204 = {
  data: void
  status: 204
}

export type changeCourseStudentsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type changeCourseStudentsResponse401 = {
  data: void
  status: 401
}

export type changeCourseStudentsResponse403 = {
  data: void
  status: 403
}

export type changeCourseStudentsResponseSuccess = (changeCourseStudentsResponse204) & {
  headers: Headers;
};
export type changeCourseStudentsResponseError = (changeCourseStudentsResponse400 | changeCourseStudentsResponse401 | changeCourseStudentsResponse403) & {
  headers: Headers;
};

export type changeCourseStudentsResponse = (changeCourseStudentsResponseSuccess | changeCourseStudentsResponseError)

export const getChangeCourseStudentsUrl = (courseId: string,) => {




  return `/api/v1/courses/${courseId}/students/changes`
}

/**
 * Добавляет студентов из add и снимает студентов из remove, остальных не затрагивает. Только для преподавателя-владельца; неизвестные / не привязанные id в add → 400.
 * @summary Точечное изменение студентов курса
 */
export const changeCourseStudents = async (courseId: string,
    changeStudentsRequest: ChangeStudentsRequest, options?: Parameters<typeof educationFetch>[1]): Promise<changeCourseStudentsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<changeCourseStudentsResponse>(getChangeCourseStudentsUrl(courseId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(changeStudentsRequest)
  }
);}





export const getChangeCourseStudentsMutationKey = () => ['changeCourseStudents'] as const;

export const getChangeCourseStudentsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeCourseStudents>>, TError,ChangeCourseStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changeCourseStudents>>, TError,ChangeCourseStudentsMutationVariables, TContext> => {

const mutationKey = getChangeCourseStudentsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changeCourseStudents>>, ChangeCourseStudentsMutationVariables> = (props) => {
          const {courseId,data} = props ?? {};

          return  changeCourseStudents(courseId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChangeCourseStudentsMutationResult = NonNullable<Awaited<ReturnType<typeof changeCourseStudents>>>
    export type ChangeCourseStudentsMutationBody = ChangeStudentsRequest
    export type ChangeCourseStudentsMutationError = ProblemDetails | void
    export type ChangeCourseStudentsMutationVariables = {courseId: string;data: ChangeStudentsRequest}

    /**
 * @summary Точечное изменение студентов курса
 */
export const useChangeCourseStudents = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changeCourseStudents>>, TError,ChangeCourseStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changeCourseStudents>>,
        TError,
        ChangeCourseStudentsMutationVariables,
        TContext
      > => {
      return useMutation(getChangeCourseStudentsMutationOptions(options), queryClient);
    }
    export type changePracticalStudentsResponse204 = {
  data: void
  status: 204
}

export type changePracticalStudentsResponse400 = {
  data: ProblemDetails
  status: 400
}

export type changePracticalStudentsResponse401 = {
  data: void
  status: 401
}

export type changePracticalStudentsResponse403 = {
  data: void
  status: 403
}

export type changePracticalStudentsResponseSuccess = (changePracticalStudentsResponse204) & {
  headers: Headers;
};
export type changePracticalStudentsResponseError = (changePracticalStudentsResponse400 | changePracticalStudentsResponse401 | changePracticalStudentsResponse403) & {
  headers: Headers;
};

export type changePracticalStudentsResponse = (changePracticalStudentsResponseSuccess | changePracticalStudentsResponseError)

export const getChangePracticalStudentsUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/students/changes`
}

/**
 * Добавляет студентов из add и снимает студентов из remove, остальных не затрагивает. Только для преподавателя-владельца; неизвестные / не привязанные id в add → 400.
 * @summary Точечное изменение студентов практики
 */
export const changePracticalStudents = async (practicalId: string,
    changeStudentsRequest: ChangeStudentsRequest, options?: Parameters<typeof educationFetch>[1]): Promise<changePracticalStudentsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<changePracticalStudentsResponse>(getChangePracticalStudentsUrl(practicalId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(changeStudentsRequest)
  }
);}





export const getChangePracticalStudentsMutationKey = () => ['changePracticalStudents'] as const;

export const getChangePracticalStudentsMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePracticalStudents>>, TError,ChangePracticalStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changePracticalStudents>>, TError,ChangePracticalStudentsMutationVariables, TContext> => {

const mutationKey = getChangePracticalStudentsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePracticalStudents>>, ChangePracticalStudentsMutationVariables> = (props) => {
          const {practicalId,data} = props ?? {};

          return  changePracticalStudents(practicalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChangePracticalStudentsMutationResult = NonNullable<Awaited<ReturnType<typeof changePracticalStudents>>>
    export type ChangePracticalStudentsMutationBody = ChangeStudentsRequest
    export type ChangePracticalStudentsMutationError = ProblemDetails | void
    export type ChangePracticalStudentsMutationVariables = {practicalId: string;data: ChangeStudentsRequest}

    /**
 * @summary Точечное изменение студентов практики
 */
export const useChangePracticalStudents = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePracticalStudents>>, TError,ChangePracticalStudentsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePracticalStudents>>,
        TError,
        ChangePracticalStudentsMutationVariables,
        TContext
      > => {
      return useMutation(getChangePracticalStudentsMutationOptions(options), queryClient);
    }
