/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  LoginRequest,
  ProblemDetails,
  RefreshRequest,
  RegisterRequest,
  TokenResponse,
  ValidationProblemDetails
} from '../model';

import { identityFetch } from '../../../shared/http/identity-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type registerResponse201 = {
  data: TokenResponse
  status: 201
}

export type registerResponse409 = {
  data: ProblemDetails
  status: 409
}

export type registerResponse422 = {
  data: ValidationProblemDetails
  status: 422
}

export type registerResponseSuccess = (registerResponse201) & {
  headers: Headers;
};
export type registerResponseError = (registerResponse409 | registerResponse422) & {
  headers: Headers;
};

export type registerResponse = (registerResponseSuccess | registerResponseError)

export const getRegisterUrl = () => {




  return `/api/v1/auth/register`
}

/**
 * Создаёт пользователя с ролью Student и возвращает пару токенов.
 * @summary Регистрация нового пользователя
 */
export const register = async (registerRequest: RegisterRequest, options?: Parameters<typeof identityFetch>[1]): Promise<registerResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return identityFetch<registerResponse>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerRequest)
  }
);}





export const getRegisterMutationKey = () => ['register'] as const;

export const getRegisterMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,RegisterMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,RegisterMutationVariables, TContext> => {

const mutationKey = getRegisterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, RegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterRequest
    export type RegisterMutationError = ProblemDetails | ValidationProblemDetails
    export type RegisterMutationVariables = {data: RegisterRequest}

    /**
 * @summary Регистрация нового пользователя
 */
export const useRegister = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,RegisterMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        RegisterMutationVariables,
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }
    export type refreshResponse200 = {
  data: TokenResponse
  status: 200
}

export type refreshResponse401 = {
  data: ProblemDetails
  status: 401
}

export type refreshResponse422 = {
  data: ValidationProblemDetails
  status: 422
}

export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponse401 | refreshResponse422) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {




  return `/api/v1/auth/refresh`
}

/**
 * Ротирует refresh-токен. Повторное использование отозванного токена инициирует отзыв всех сессий.
 * @summary Обновление токенов
 */
export const refresh = async (refreshRequest: RefreshRequest, options?: Parameters<typeof identityFetch>[1]): Promise<refreshResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return identityFetch<refreshResponse>(getRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(refreshRequest)
  }
);}





export const getRefreshMutationKey = () => ['refresh'] as const;

export const getRefreshMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,RefreshMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,RefreshMutationVariables, TContext> => {

const mutationKey = getRefreshMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refresh>>, RefreshMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  refresh(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshMutationResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
    export type RefreshMutationBody = RefreshRequest
    export type RefreshMutationError = ProblemDetails | ValidationProblemDetails
    export type RefreshMutationVariables = {data: RefreshRequest}

    /**
 * @summary Обновление токенов
 */
export const useRefresh = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,RefreshMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refresh>>,
        TError,
        RefreshMutationVariables,
        TContext
      > => {
      return useMutation(getRefreshMutationOptions(options), queryClient);
    }
    export type logoutResponse204 = {
  data: void
  status: 204
}

export type logoutResponse422 = {
  data: ValidationProblemDetails
  status: 422
}

export type logoutResponseSuccess = (logoutResponse204) & {
  headers: Headers;
};
export type logoutResponseError = (logoutResponse422) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseSuccess | logoutResponseError)

export const getLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * Отзывает refresh-токен. Идемпотентно: повторный вызов возвращает 204.
 * @summary Выход из системы
 */
export const logout = async (refreshRequest: RefreshRequest, options?: Parameters<typeof identityFetch>[1]): Promise<logoutResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return identityFetch<logoutResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(refreshRequest)
  }
);}





export const getLogoutMutationKey = () => ['logout'] as const;

export const getLogoutMutationOptions = <TError = ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,LogoutMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,LogoutMutationVariables, TContext> => {

const mutationKey = getLogoutMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, LogoutMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  logout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    export type LogoutMutationBody = RefreshRequest
    export type LogoutMutationError = ValidationProblemDetails
    export type LogoutMutationVariables = {data: RefreshRequest}

    /**
 * @summary Выход из системы
 */
export const useLogout = <TError = ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,LogoutMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        LogoutMutationVariables,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options), queryClient);
    }
    export type loginResponse200 = {
  data: TokenResponse
  status: 200
}

export type loginResponse401 = {
  data: ProblemDetails
  status: 401
}

export type loginResponse422 = {
  data: ValidationProblemDetails
  status: 422
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401 | loginResponse422) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * Проверяет учётные данные и возвращает пару токенов.
 * @summary Аутентификация пользователя
 */
export const login = async (loginRequest: LoginRequest, options?: Parameters<typeof identityFetch>[1]): Promise<loginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return identityFetch<loginResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequest)
  }
);}





export const getLoginMutationKey = () => ['login'] as const;

export const getLoginMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext> => {

const mutationKey = getLoginMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, LoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = ProblemDetails | ValidationProblemDetails
    export type LoginMutationVariables = {data: LoginRequest}

    /**
 * @summary Аутентификация пользователя
 */
export const useLogin = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        LoginMutationVariables,
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
