/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateQuestionRequest,
  HttpValidationProblemDetails,
  QuestionResponse,
  UpdateQuestionRequest
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getModuleQuestionsResponse200 = {
  data: QuestionResponse[]
  status: 200
}

export type getModuleQuestionsResponse401 = {
  data: void
  status: 401
}

export type getModuleQuestionsResponse403 = {
  data: void
  status: 403
}

export type getModuleQuestionsResponseSuccess = (getModuleQuestionsResponse200) & {
  headers: Headers;
};
export type getModuleQuestionsResponseError = (getModuleQuestionsResponse401 | getModuleQuestionsResponse403) & {
  headers: Headers;
};

export type getModuleQuestionsResponse = (getModuleQuestionsResponseSuccess | getModuleQuestionsResponseError)

export const getGetModuleQuestionsUrl = (moduleId: string,) => {




  return `/api/v1/modules/${moduleId}/questions`
}

/**
 * Возвращает вопросы, созданные преподавателем для выбранного модуля.
 * @summary Получение вопросов модуля
 */
export const getModuleQuestions = async (moduleId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getModuleQuestionsResponse> => {

  return educationFetch<getModuleQuestionsResponse>(getGetModuleQuestionsUrl(moduleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetModuleQuestionsQueryKey = (moduleId: string,) => {
    return [
    `/api/v1/modules/${moduleId}/questions`
    ] as const;
    }


export const getGetModuleQuestionsQueryOptions = <TData = Awaited<ReturnType<typeof getModuleQuestions>>, TError = void>(moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleQuestions>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModuleQuestionsQueryKey(moduleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleQuestions>>> = ({ signal }) => getModuleQuestions(moduleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: moduleId !== null && moduleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModuleQuestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModuleQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getModuleQuestions>>>
export type GetModuleQuestionsQueryError = void


export function useGetModuleQuestions<TData = Awaited<ReturnType<typeof getModuleQuestions>>, TError = void>(
 moduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleQuestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleQuestions>>,
          TError,
          Awaited<ReturnType<typeof getModuleQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleQuestions<TData = Awaited<ReturnType<typeof getModuleQuestions>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleQuestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleQuestions>>,
          TError,
          Awaited<ReturnType<typeof getModuleQuestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleQuestions<TData = Awaited<ReturnType<typeof getModuleQuestions>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleQuestions>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение вопросов модуля
 */

export function useGetModuleQuestions<TData = Awaited<ReturnType<typeof getModuleQuestions>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleQuestions>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModuleQuestionsQueryOptions(moduleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createQuestionResponse200 = {
  data: QuestionResponse
  status: 200
}

export type createQuestionResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createQuestionResponse401 = {
  data: void
  status: 401
}

export type createQuestionResponse403 = {
  data: void
  status: 403
}

export type createQuestionResponse404 = {
  data: void
  status: 404
}

export type createQuestionResponseSuccess = (createQuestionResponse200) & {
  headers: Headers;
};
export type createQuestionResponseError = (createQuestionResponse400 | createQuestionResponse401 | createQuestionResponse403 | createQuestionResponse404) & {
  headers: Headers;
};

export type createQuestionResponse = (createQuestionResponseSuccess | createQuestionResponseError)

export const getCreateQuestionUrl = () => {




  return `/api/v1/questions`
}

/**
 * Создаёт вопрос для тестирования внутри модуля преподавателя.
 * @summary Создание вопроса
 */
export const createQuestion = async (createQuestionRequest: CreateQuestionRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createQuestionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createQuestionResponse>(getCreateQuestionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createQuestionRequest)
  }
);}





export const getCreateQuestionMutationKey = () => ['createQuestion'] as const;

export const getCreateQuestionMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQuestion>>, TError,CreateQuestionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createQuestion>>, TError,CreateQuestionMutationVariables, TContext> => {

const mutationKey = getCreateQuestionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createQuestion>>, CreateQuestionMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createQuestion(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof createQuestion>>>
    export type CreateQuestionMutationBody = CreateQuestionRequest
    export type CreateQuestionMutationError = HttpValidationProblemDetails | void
    export type CreateQuestionMutationVariables = {data: CreateQuestionRequest}

    /**
 * @summary Создание вопроса
 */
export const useCreateQuestion = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQuestion>>, TError,CreateQuestionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createQuestion>>,
        TError,
        CreateQuestionMutationVariables,
        TContext
      > => {
      return useMutation(getCreateQuestionMutationOptions(options), queryClient);
    }
    export type updateQuestionResponse204 = {
  data: void
  status: 204
}

export type updateQuestionResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateQuestionResponse401 = {
  data: void
  status: 401
}

export type updateQuestionResponse403 = {
  data: void
  status: 403
}

export type updateQuestionResponse404 = {
  data: void
  status: 404
}

export type updateQuestionResponseSuccess = (updateQuestionResponse204) & {
  headers: Headers;
};
export type updateQuestionResponseError = (updateQuestionResponse400 | updateQuestionResponse401 | updateQuestionResponse403 | updateQuestionResponse404) & {
  headers: Headers;
};

export type updateQuestionResponse = (updateQuestionResponseSuccess | updateQuestionResponseError)

export const getUpdateQuestionUrl = (questionId: string,) => {




  return `/api/v1/questions/${questionId}`
}

/**
 * Изменяет текст, тело, ответ, вес и тип вопроса.
 * @summary Обновление вопроса
 */
export const updateQuestion = async (questionId: string,
    updateQuestionRequest: UpdateQuestionRequest, options?: Parameters<typeof educationFetch>[1]): Promise<updateQuestionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<updateQuestionResponse>(getUpdateQuestionUrl(questionId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateQuestionRequest)
  }
);}





export const getUpdateQuestionMutationKey = () => ['updateQuestion'] as const;

export const getUpdateQuestionMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuestion>>, TError,UpdateQuestionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateQuestion>>, TError,UpdateQuestionMutationVariables, TContext> => {

const mutationKey = getUpdateQuestionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateQuestion>>, UpdateQuestionMutationVariables> = (props) => {
          const {questionId,data} = props ?? {};

          return  updateQuestion(questionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuestion>>>
    export type UpdateQuestionMutationBody = UpdateQuestionRequest
    export type UpdateQuestionMutationError = HttpValidationProblemDetails | void
    export type UpdateQuestionMutationVariables = {questionId: string;data: UpdateQuestionRequest}

    /**
 * @summary Обновление вопроса
 */
export const useUpdateQuestion = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuestion>>, TError,UpdateQuestionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateQuestion>>,
        TError,
        UpdateQuestionMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateQuestionMutationOptions(options), queryClient);
    }
    export type deleteQuestionResponse204 = {
  data: void
  status: 204
}

export type deleteQuestionResponse401 = {
  data: void
  status: 401
}

export type deleteQuestionResponse403 = {
  data: void
  status: 403
}

export type deleteQuestionResponse404 = {
  data: void
  status: 404
}

export type deleteQuestionResponseSuccess = (deleteQuestionResponse204) & {
  headers: Headers;
};
export type deleteQuestionResponseError = (deleteQuestionResponse401 | deleteQuestionResponse403 | deleteQuestionResponse404) & {
  headers: Headers;
};

export type deleteQuestionResponse = (deleteQuestionResponseSuccess | deleteQuestionResponseError)

export const getDeleteQuestionUrl = (questionId: string,) => {




  return `/api/v1/questions/${questionId}`
}

/**
 * Удаляет вопрос преподавателя из банка вопросов.
 * @summary Удаление вопроса
 */
export const deleteQuestion = async (questionId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deleteQuestionResponse> => {

  return educationFetch<deleteQuestionResponse>(getDeleteQuestionUrl(questionId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteQuestionMutationKey = () => ['deleteQuestion'] as const;

export const getDeleteQuestionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQuestion>>, TError,DeleteQuestionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteQuestion>>, TError,DeleteQuestionMutationVariables, TContext> => {

const mutationKey = getDeleteQuestionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQuestion>>, DeleteQuestionMutationVariables> = (props) => {
          const {questionId} = props ?? {};

          return  deleteQuestion(questionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQuestion>>>

    export type DeleteQuestionMutationError = void
    export type DeleteQuestionMutationVariables = {questionId: string}

    /**
 * @summary Удаление вопроса
 */
export const useDeleteQuestion = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQuestion>>, TError,DeleteQuestionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteQuestion>>,
        TError,
        DeleteQuestionMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteQuestionMutationOptions(options), queryClient);
    }
