/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompleteModuleSessionRequest,
  CurrentModuleSessionResponse,
  GetCurrentModuleSessionParams,
  ModuleSessionEventResponse,
  ModuleSessionResponse,
  ModuleSessionSummaryResponse,
  StartModuleSessionRequest,
  StartModuleSessionResponse
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type startModuleSessionResponse200 = {
  data: StartModuleSessionResponse
  status: 200
}

export type startModuleSessionResponse401 = {
  data: void
  status: 401
}

export type startModuleSessionResponse403 = {
  data: void
  status: 403
}

export type startModuleSessionResponse404 = {
  data: void
  status: 404
}

export type startModuleSessionResponse409 = {
  data: void
  status: 409
}

export type startModuleSessionResponse502 = {
  data: void
  status: 502
}

export type startModuleSessionResponseSuccess = (startModuleSessionResponse200) & {
  headers: Headers;
};
export type startModuleSessionResponseError = (startModuleSessionResponse401 | startModuleSessionResponse403 | startModuleSessionResponse404 | startModuleSessionResponse409 | startModuleSessionResponse502) & {
  headers: Headers;
};

export type startModuleSessionResponse = (startModuleSessionResponseSuccess | startModuleSessionResponseError)

export const getStartModuleSessionUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/module-sessions`
}

/**
 * @summary Запуск/продолжение попытки внешнего модуля
 */
export const startModuleSession = async (practicalId: string,
    startModuleSessionRequest: StartModuleSessionRequest, options?: Parameters<typeof educationFetch>[1]): Promise<startModuleSessionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<startModuleSessionResponse>(getStartModuleSessionUrl(practicalId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(startModuleSessionRequest)
  }
);}





export const getStartModuleSessionMutationKey = () => ['startModuleSession'] as const;

export const getStartModuleSessionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startModuleSession>>, TError,StartModuleSessionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof startModuleSession>>, TError,StartModuleSessionMutationVariables, TContext> => {

const mutationKey = getStartModuleSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startModuleSession>>, StartModuleSessionMutationVariables> = (props) => {
          const {practicalId,data} = props ?? {};

          return  startModuleSession(practicalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartModuleSessionMutationResult = NonNullable<Awaited<ReturnType<typeof startModuleSession>>>
    export type StartModuleSessionMutationBody = StartModuleSessionRequest
    export type StartModuleSessionMutationError = void
    export type StartModuleSessionMutationVariables = {practicalId: string;data: StartModuleSessionRequest}

    /**
 * @summary Запуск/продолжение попытки внешнего модуля
 */
export const useStartModuleSession = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startModuleSession>>, TError,StartModuleSessionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startModuleSession>>,
        TError,
        StartModuleSessionMutationVariables,
        TContext
      > => {
      return useMutation(getStartModuleSessionMutationOptions(options), queryClient);
    }
    export type listPracticalModuleSessionsResponse200 = {
  data: ModuleSessionSummaryResponse[]
  status: 200
}

export type listPracticalModuleSessionsResponse401 = {
  data: void
  status: 401
}

export type listPracticalModuleSessionsResponse403 = {
  data: void
  status: 403
}

export type listPracticalModuleSessionsResponse404 = {
  data: void
  status: 404
}

export type listPracticalModuleSessionsResponseSuccess = (listPracticalModuleSessionsResponse200) & {
  headers: Headers;
};
export type listPracticalModuleSessionsResponseError = (listPracticalModuleSessionsResponse401 | listPracticalModuleSessionsResponse403 | listPracticalModuleSessionsResponse404) & {
  headers: Headers;
};

export type listPracticalModuleSessionsResponse = (listPracticalModuleSessionsResponseSuccess | listPracticalModuleSessionsResponseError)

export const getListPracticalModuleSessionsUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/module-sessions`
}

/**
 * Все попытки студентов по практике. Доступ: преподаватель — владелец курса практики.
 * @summary Список попыток внешнего модуля по практике (преподаватель)
 */
export const listPracticalModuleSessions = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<listPracticalModuleSessionsResponse> => {

  return educationFetch<listPracticalModuleSessionsResponse>(getListPracticalModuleSessionsUrl(practicalId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPracticalModuleSessionsQueryKey = (practicalId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/module-sessions`
    ] as const;
    }


export const getListPracticalModuleSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError = void>(practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPracticalModuleSessionsQueryKey(practicalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPracticalModuleSessions>>> = ({ signal }) => listPracticalModuleSessions(practicalId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPracticalModuleSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listPracticalModuleSessions>>>
export type ListPracticalModuleSessionsQueryError = void


export function useListPracticalModuleSessions<TData = Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError = void>(
 practicalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPracticalModuleSessions>>,
          TError,
          Awaited<ReturnType<typeof listPracticalModuleSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPracticalModuleSessions<TData = Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPracticalModuleSessions>>,
          TError,
          Awaited<ReturnType<typeof listPracticalModuleSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPracticalModuleSessions<TData = Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Список попыток внешнего модуля по практике (преподаватель)
 */

export function useListPracticalModuleSessions<TData = Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPracticalModuleSessions>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPracticalModuleSessionsQueryOptions(practicalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCurrentModuleSessionResponse200 = {
  data: CurrentModuleSessionResponse
  status: 200
}

export type getCurrentModuleSessionResponse401 = {
  data: void
  status: 401
}

export type getCurrentModuleSessionResponse403 = {
  data: void
  status: 403
}

export type getCurrentModuleSessionResponse404 = {
  data: void
  status: 404
}

export type getCurrentModuleSessionResponseSuccess = (getCurrentModuleSessionResponse200) & {
  headers: Headers;
};
export type getCurrentModuleSessionResponseError = (getCurrentModuleSessionResponse401 | getCurrentModuleSessionResponse403 | getCurrentModuleSessionResponse404) & {
  headers: Headers;
};

export type getCurrentModuleSessionResponse = (getCurrentModuleSessionResponseSuccess | getCurrentModuleSessionResponseError)

export const getGetCurrentModuleSessionUrl = (practicalId: string,
    params: GetCurrentModuleSessionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/practicals/${practicalId}/module-sessions/current?${stringifiedParams}` : `/api/v1/practicals/${practicalId}/module-sessions/current`
}

/**
 * @summary Гейт кнопок запуска внешней практики
 */
export const getCurrentModuleSession = async (practicalId: string,
    params: GetCurrentModuleSessionParams, options?: Parameters<typeof educationFetch>[1]): Promise<getCurrentModuleSessionResponse> => {

  return educationFetch<getCurrentModuleSessionResponse>(getGetCurrentModuleSessionUrl(practicalId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCurrentModuleSessionQueryKey = (practicalId: string,
    params?: GetCurrentModuleSessionParams,) => {
    return [
    `/api/v1/practicals/${practicalId}/module-sessions/current`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCurrentModuleSessionQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = void>(practicalId: string,
    params: GetCurrentModuleSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentModuleSessionQueryKey(practicalId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentModuleSession>>> = ({ signal }) => getCurrentModuleSession(practicalId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentModuleSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentModuleSession>>>
export type GetCurrentModuleSessionQueryError = void


export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = void>(
 practicalId: string,
    params: GetCurrentModuleSessionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentModuleSession>>,
          TError,
          Awaited<ReturnType<typeof getCurrentModuleSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = void>(
 practicalId: string,
    params: GetCurrentModuleSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentModuleSession>>,
          TError,
          Awaited<ReturnType<typeof getCurrentModuleSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = void>(
 practicalId: string,
    params: GetCurrentModuleSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Гейт кнопок запуска внешней практики
 */

export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = void>(
 practicalId: string,
    params: GetCurrentModuleSessionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentModuleSessionQueryOptions(practicalId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getModuleSessionResponse200 = {
  data: ModuleSessionResponse
  status: 200
}

export type getModuleSessionResponse401 = {
  data: void
  status: 401
}

export type getModuleSessionResponse403 = {
  data: void
  status: 403
}

export type getModuleSessionResponse404 = {
  data: void
  status: 404
}

export type getModuleSessionResponseSuccess = (getModuleSessionResponse200) & {
  headers: Headers;
};
export type getModuleSessionResponseError = (getModuleSessionResponse401 | getModuleSessionResponse403 | getModuleSessionResponse404) & {
  headers: Headers;
};

export type getModuleSessionResponse = (getModuleSessionResponseSuccess | getModuleSessionResponseError)

export const getGetModuleSessionUrl = (practicalId: string,
    sessionId: string,) => {




  return `/api/v1/practicals/${practicalId}/module-sessions/${sessionId}`
}

/**
 * @summary Статус попытки внешнего модуля
 */
export const getModuleSession = async (practicalId: string,
    sessionId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getModuleSessionResponse> => {

  return educationFetch<getModuleSessionResponse>(getGetModuleSessionUrl(practicalId,sessionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetModuleSessionQueryKey = (practicalId: string,
    sessionId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/module-sessions/${sessionId}`
    ] as const;
    }


export const getGetModuleSessionQueryOptions = <TData = Awaited<ReturnType<typeof getModuleSession>>, TError = void>(practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSession>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModuleSessionQueryKey(practicalId,sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleSession>>> = ({ signal }) => getModuleSession(practicalId,sessionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined && sessionId !== null && sessionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModuleSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModuleSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getModuleSession>>>
export type GetModuleSessionQueryError = void


export function useGetModuleSession<TData = Awaited<ReturnType<typeof getModuleSession>>, TError = void>(
 practicalId: string,
    sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleSession>>,
          TError,
          Awaited<ReturnType<typeof getModuleSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleSession<TData = Awaited<ReturnType<typeof getModuleSession>>, TError = void>(
 practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleSession>>,
          TError,
          Awaited<ReturnType<typeof getModuleSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleSession<TData = Awaited<ReturnType<typeof getModuleSession>>, TError = void>(
 practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSession>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Статус попытки внешнего модуля
 */

export function useGetModuleSession<TData = Awaited<ReturnType<typeof getModuleSession>>, TError = void>(
 practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSession>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModuleSessionQueryOptions(practicalId,sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type abandonModuleSessionResponse204 = {
  data: void
  status: 204
}

export type abandonModuleSessionResponse401 = {
  data: void
  status: 401
}

export type abandonModuleSessionResponse403 = {
  data: void
  status: 403
}

export type abandonModuleSessionResponse404 = {
  data: void
  status: 404
}

export type abandonModuleSessionResponse409 = {
  data: void
  status: 409
}

export type abandonModuleSessionResponseSuccess = (abandonModuleSessionResponse204) & {
  headers: Headers;
};
export type abandonModuleSessionResponseError = (abandonModuleSessionResponse401 | abandonModuleSessionResponse403 | abandonModuleSessionResponse404 | abandonModuleSessionResponse409) & {
  headers: Headers;
};

export type abandonModuleSessionResponse = (abandonModuleSessionResponseSuccess | abandonModuleSessionResponseError)

export const getAbandonModuleSessionUrl = (practicalId: string,
    sessionId: string,) => {




  return `/api/v1/practicals/${practicalId}/module-sessions/${sessionId}/abandon`
}

/**
 * @summary Прервать попытку внешнего модуля
 */
export const abandonModuleSession = async (practicalId: string,
    sessionId: string, options?: Parameters<typeof educationFetch>[1]): Promise<abandonModuleSessionResponse> => {

  return educationFetch<abandonModuleSessionResponse>(getAbandonModuleSessionUrl(practicalId,sessionId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAbandonModuleSessionMutationKey = () => ['abandonModuleSession'] as const;

export const getAbandonModuleSessionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof abandonModuleSession>>, TError,AbandonModuleSessionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof abandonModuleSession>>, TError,AbandonModuleSessionMutationVariables, TContext> => {

const mutationKey = getAbandonModuleSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof abandonModuleSession>>, AbandonModuleSessionMutationVariables> = (props) => {
          const {practicalId,sessionId} = props ?? {};

          return  abandonModuleSession(practicalId,sessionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AbandonModuleSessionMutationResult = NonNullable<Awaited<ReturnType<typeof abandonModuleSession>>>

    export type AbandonModuleSessionMutationError = void
    export type AbandonModuleSessionMutationVariables = {practicalId: string;sessionId: string}

    /**
 * @summary Прервать попытку внешнего модуля
 */
export const useAbandonModuleSession = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof abandonModuleSession>>, TError,AbandonModuleSessionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof abandonModuleSession>>,
        TError,
        AbandonModuleSessionMutationVariables,
        TContext
      > => {
      return useMutation(getAbandonModuleSessionMutationOptions(options), queryClient);
    }
    export type getModuleSessionEventsResponse200 = {
  data: ModuleSessionEventResponse[]
  status: 200
}

export type getModuleSessionEventsResponse401 = {
  data: void
  status: 401
}

export type getModuleSessionEventsResponse403 = {
  data: void
  status: 403
}

export type getModuleSessionEventsResponse404 = {
  data: void
  status: 404
}

export type getModuleSessionEventsResponseSuccess = (getModuleSessionEventsResponse200) & {
  headers: Headers;
};
export type getModuleSessionEventsResponseError = (getModuleSessionEventsResponse401 | getModuleSessionEventsResponse403 | getModuleSessionEventsResponse404) & {
  headers: Headers;
};

export type getModuleSessionEventsResponse = (getModuleSessionEventsResponseSuccess | getModuleSessionEventsResponseError)

export const getGetModuleSessionEventsUrl = (practicalId: string,
    sessionId: string,) => {




  return `/api/v1/practicals/${practicalId}/module-sessions/${sessionId}/events`
}

/**
 * «Цифровой след» попытки. Доступ: владелец сессии или преподаватель курса практики.
 * @summary Лента событий попытки внешнего модуля
 */
export const getModuleSessionEvents = async (practicalId: string,
    sessionId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getModuleSessionEventsResponse> => {

  return educationFetch<getModuleSessionEventsResponse>(getGetModuleSessionEventsUrl(practicalId,sessionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetModuleSessionEventsQueryKey = (practicalId: string,
    sessionId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/module-sessions/${sessionId}/events`
    ] as const;
    }


export const getGetModuleSessionEventsQueryOptions = <TData = Awaited<ReturnType<typeof getModuleSessionEvents>>, TError = void>(practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSessionEvents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModuleSessionEventsQueryKey(practicalId,sessionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleSessionEvents>>> = ({ signal }) => getModuleSessionEvents(practicalId,sessionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined && sessionId !== null && sessionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModuleSessionEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModuleSessionEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getModuleSessionEvents>>>
export type GetModuleSessionEventsQueryError = void


export function useGetModuleSessionEvents<TData = Awaited<ReturnType<typeof getModuleSessionEvents>>, TError = void>(
 practicalId: string,
    sessionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSessionEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleSessionEvents>>,
          TError,
          Awaited<ReturnType<typeof getModuleSessionEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleSessionEvents<TData = Awaited<ReturnType<typeof getModuleSessionEvents>>, TError = void>(
 practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSessionEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleSessionEvents>>,
          TError,
          Awaited<ReturnType<typeof getModuleSessionEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleSessionEvents<TData = Awaited<ReturnType<typeof getModuleSessionEvents>>, TError = void>(
 practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSessionEvents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Лента событий попытки внешнего модуля
 */

export function useGetModuleSessionEvents<TData = Awaited<ReturnType<typeof getModuleSessionEvents>>, TError = void>(
 practicalId: string,
    sessionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleSessionEvents>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModuleSessionEventsQueryOptions(practicalId,sessionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type completeModuleSessionResponse200 = {
  data: void
  status: 200
}

export type completeModuleSessionResponse401 = {
  data: void
  status: 401
}

export type completeModuleSessionResponse409 = {
  data: void
  status: 409
}

export type completeModuleSessionResponseSuccess = (completeModuleSessionResponse200) & {
  headers: Headers;
};
export type completeModuleSessionResponseError = (completeModuleSessionResponse401 | completeModuleSessionResponse409) & {
  headers: Headers;
};

export type completeModuleSessionResponse = (completeModuleSessionResponseSuccess | completeModuleSessionResponseError)

export const getCompleteModuleSessionUrl = (sessionId: string,) => {




  return `/api/v1/module-sessions/${sessionId}/complete`
}

/**
 * @summary Приём оценки от бэкенда модуля
 */
export const completeModuleSession = async (sessionId: string,
    completeModuleSessionRequest: CompleteModuleSessionRequest, options?: Parameters<typeof educationFetch>[1]): Promise<completeModuleSessionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<completeModuleSessionResponse>(getCompleteModuleSessionUrl(sessionId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(completeModuleSessionRequest)
  }
);}





export const getCompleteModuleSessionMutationKey = () => ['completeModuleSession'] as const;

export const getCompleteModuleSessionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeModuleSession>>, TError,CompleteModuleSessionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeModuleSession>>, TError,CompleteModuleSessionMutationVariables, TContext> => {

const mutationKey = getCompleteModuleSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeModuleSession>>, CompleteModuleSessionMutationVariables> = (props) => {
          const {sessionId,data} = props ?? {};

          return  completeModuleSession(sessionId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteModuleSessionMutationResult = NonNullable<Awaited<ReturnType<typeof completeModuleSession>>>
    export type CompleteModuleSessionMutationBody = CompleteModuleSessionRequest
    export type CompleteModuleSessionMutationError = void
    export type CompleteModuleSessionMutationVariables = {sessionId: string;data: CompleteModuleSessionRequest}

    /**
 * @summary Приём оценки от бэкенда модуля
 */
export const useCompleteModuleSession = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeModuleSession>>, TError,CompleteModuleSessionMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeModuleSession>>,
        TError,
        CompleteModuleSessionMutationVariables,
        TContext
      > => {
      return useMutation(getCompleteModuleSessionMutationOptions(options), queryClient);
    }
