/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Событие безопасности или административное действие.
 */
export interface AuditEventDto {
  id: string;
  /** @nullable */
  actorUserId?: string | null;
  /** @nullable */
  targetUserId?: string | null;
  eventType: string;
  description: string;
  createdAt: string;
}
