/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

export type GetUserActivityParams = {
Page?: number;
PageSize?: number;
EventType?: string;
From?: string;
To?: string;
};
