/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

export type ListUsersParams = {
Page?: number;
PageSize?: number;
Search?: string;
Role?: string;
Status?: string;
};
