/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Запрос на регистрацию нового пользователя.
 */
export interface RegisterRequest {
  email: string;
  password: string;
  /** @nullable */
  displayName?: string | null;
}
