/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обмен токена пользователя на токен, ограниченный аудиторией другого сервиса
 * (RFC 8693-style). Аутентификация вызывающего клиента — заголовком
 * `Authorization: Basic base64(client_id:client_secret)`, не телом запроса.
 */
export interface TokenExchangeRequest {
  /** Всегда `urn:ietf:params:oauth:grant-type:token-exchange`. */
  grantType: string;
  /** Валидный токен пользователя, выданный этим инстансом. */
  subjectToken: string;
  /** Целевая аудитория (должна быть в allow-list клиента). */
  audience: string;
  /**
     * Необязательный идентификатор практической сессии (передаёт Education). При наличии
     * попадает в выпускаемый токен как claim `session_id` — бэкенд внешнего модуля
     * по нему привязывает вызовы к платформенной сессии.
     * @nullable
     */
  sessionId?: string | null;
  /**
     * Необязательное время истечения практической сессии. Если раньше стандартного TTL
     * обменянного токена — `exp` токена обрезается по нему.
     * @nullable
     */
  sessionExpiresAt?: string | null;
}
