/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Ответ на обмен токена. Только access-токен — Token Exchange не выпускает refresh-токен,
 * обменянный токен одноразовый по смыслу и живёт ровно на длительность запуска.
 */
export interface TokenExchangeResponse {
  accessToken: string;
  expiresIn: number;
}
