/**
 * Generated by orval 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

export type ValidationProblemDetailsErrors = {[key: string]: string[]};
