/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConfigurePracticalQuestionsRequest,
  CreatePracticalRequest,
  CreateTaskRequest,
  HttpValidationProblemDetails,
  PracticalQuestionsSetupResponse,
  PracticalResponse,
  TaskResponse,
  UpdateTaskTextRequest
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getModulePracticalsResponse200 = {
  data: PracticalResponse[]
  status: 200
}

export type getModulePracticalsResponse401 = {
  data: void
  status: 401
}

export type getModulePracticalsResponse403 = {
  data: void
  status: 403
}

export type getModulePracticalsResponseSuccess = (getModulePracticalsResponse200) & {
  headers: Headers;
};
export type getModulePracticalsResponseError = (getModulePracticalsResponse401 | getModulePracticalsResponse403) & {
  headers: Headers;
};

export type getModulePracticalsResponse = (getModulePracticalsResponseSuccess | getModulePracticalsResponseError)

export const getGetModulePracticalsUrl = (moduleId: string,) => {




  return `/api/v1/modules/${moduleId}/practicals`
}

/**
 * Возвращает практические задания выбранного модуля.
 * @summary Получение практик модуля
 */
export const getModulePracticals = async (moduleId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getModulePracticalsResponse> => {

  return educationFetch<getModulePracticalsResponse>(getGetModulePracticalsUrl(moduleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetModulePracticalsQueryKey = (moduleId: string,) => {
    return [
    `/api/v1/modules/${moduleId}/practicals`
    ] as const;
    }


export const getGetModulePracticalsQueryOptions = <TData = Awaited<ReturnType<typeof getModulePracticals>>, TError = void>(moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModulePracticals>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModulePracticalsQueryKey(moduleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModulePracticals>>> = ({ signal }) => getModulePracticals(moduleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: moduleId !== null && moduleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModulePracticals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModulePracticalsQueryResult = NonNullable<Awaited<ReturnType<typeof getModulePracticals>>>
export type GetModulePracticalsQueryError = void


export function useGetModulePracticals<TData = Awaited<ReturnType<typeof getModulePracticals>>, TError = void>(
 moduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModulePracticals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModulePracticals>>,
          TError,
          Awaited<ReturnType<typeof getModulePracticals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModulePracticals<TData = Awaited<ReturnType<typeof getModulePracticals>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModulePracticals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModulePracticals>>,
          TError,
          Awaited<ReturnType<typeof getModulePracticals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModulePracticals<TData = Awaited<ReturnType<typeof getModulePracticals>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModulePracticals>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение практик модуля
 */

export function useGetModulePracticals<TData = Awaited<ReturnType<typeof getModulePracticals>>, TError = void>(
 moduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModulePracticals>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModulePracticalsQueryOptions(moduleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createPracticalResponse200 = {
  data: PracticalResponse
  status: 200
}

export type createPracticalResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createPracticalResponse401 = {
  data: void
  status: 401
}

export type createPracticalResponse403 = {
  data: void
  status: 403
}

export type createPracticalResponse404 = {
  data: void
  status: 404
}

export type createPracticalResponseSuccess = (createPracticalResponse200) & {
  headers: Headers;
};
export type createPracticalResponseError = (createPracticalResponse400 | createPracticalResponse401 | createPracticalResponse403 | createPracticalResponse404) & {
  headers: Headers;
};

export type createPracticalResponse = (createPracticalResponseSuccess | createPracticalResponseError)

export const getCreatePracticalUrl = () => {




  return `/api/v1/practicals`
}

/**
 * Создаёт практическое задание внутри модуля преподавателя.
 * @summary Создание практики
 */
export const createPractical = async (createPracticalRequest: CreatePracticalRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createPracticalResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createPracticalResponse>(getCreatePracticalUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createPracticalRequest)
  }
);}





export const getCreatePracticalMutationKey = () => ['createPractical'] as const;

export const getCreatePracticalMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPractical>>, TError,CreatePracticalMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPractical>>, TError,CreatePracticalMutationVariables, TContext> => {

const mutationKey = getCreatePracticalMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPractical>>, CreatePracticalMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createPractical(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePracticalMutationResult = NonNullable<Awaited<ReturnType<typeof createPractical>>>
    export type CreatePracticalMutationBody = CreatePracticalRequest
    export type CreatePracticalMutationError = HttpValidationProblemDetails | void
    export type CreatePracticalMutationVariables = {data: CreatePracticalRequest}

    /**
 * @summary Создание практики
 */
export const useCreatePractical = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPractical>>, TError,CreatePracticalMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPractical>>,
        TError,
        CreatePracticalMutationVariables,
        TContext
      > => {
      return useMutation(getCreatePracticalMutationOptions(options), queryClient);
    }
    export type publishPracticalResponse204 = {
  data: void
  status: 204
}

export type publishPracticalResponse401 = {
  data: void
  status: 401
}

export type publishPracticalResponse403 = {
  data: void
  status: 403
}

export type publishPracticalResponse404 = {
  data: void
  status: 404
}

export type publishPracticalResponseSuccess = (publishPracticalResponse204) & {
  headers: Headers;
};
export type publishPracticalResponseError = (publishPracticalResponse401 | publishPracticalResponse403 | publishPracticalResponse404) & {
  headers: Headers;
};

export type publishPracticalResponse = (publishPracticalResponseSuccess | publishPracticalResponseError)

export const getPublishPracticalUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/publish`
}

/**
 * Открывает практическое задание для назначенных студентов.
 * @summary Публикация практики
 */
export const publishPractical = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<publishPracticalResponse> => {

  return educationFetch<publishPracticalResponse>(getPublishPracticalUrl(practicalId),
  {
    ...options,
    method: 'PUT'


  }
);}





export const getPublishPracticalMutationKey = () => ['publishPractical'] as const;

export const getPublishPracticalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishPractical>>, TError,PublishPracticalMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof publishPractical>>, TError,PublishPracticalMutationVariables, TContext> => {

const mutationKey = getPublishPracticalMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishPractical>>, PublishPracticalMutationVariables> = (props) => {
          const {practicalId} = props ?? {};

          return  publishPractical(practicalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishPracticalMutationResult = NonNullable<Awaited<ReturnType<typeof publishPractical>>>

    export type PublishPracticalMutationError = void
    export type PublishPracticalMutationVariables = {practicalId: string}

    /**
 * @summary Публикация практики
 */
export const usePublishPractical = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishPractical>>, TError,PublishPracticalMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishPractical>>,
        TError,
        PublishPracticalMutationVariables,
        TContext
      > => {
      return useMutation(getPublishPracticalMutationOptions(options), queryClient);
    }
    export type deletePracticalResponse204 = {
  data: void
  status: 204
}

export type deletePracticalResponse401 = {
  data: void
  status: 401
}

export type deletePracticalResponse403 = {
  data: void
  status: 403
}

export type deletePracticalResponse404 = {
  data: void
  status: 404
}

export type deletePracticalResponseSuccess = (deletePracticalResponse204) & {
  headers: Headers;
};
export type deletePracticalResponseError = (deletePracticalResponse401 | deletePracticalResponse403 | deletePracticalResponse404) & {
  headers: Headers;
};

export type deletePracticalResponse = (deletePracticalResponseSuccess | deletePracticalResponseError)

export const getDeletePracticalUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}`
}

/**
 * Удаляет практическое задание, если оно принадлежит курсу текущего преподавателя.
 * @summary Удаление практики
 */
export const deletePractical = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deletePracticalResponse> => {

  return educationFetch<deletePracticalResponse>(getDeletePracticalUrl(practicalId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePracticalMutationKey = () => ['deletePractical'] as const;

export const getDeletePracticalMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePractical>>, TError,DeletePracticalMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePractical>>, TError,DeletePracticalMutationVariables, TContext> => {

const mutationKey = getDeletePracticalMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePractical>>, DeletePracticalMutationVariables> = (props) => {
          const {practicalId} = props ?? {};

          return  deletePractical(practicalId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePracticalMutationResult = NonNullable<Awaited<ReturnType<typeof deletePractical>>>

    export type DeletePracticalMutationError = void
    export type DeletePracticalMutationVariables = {practicalId: string}

    /**
 * @summary Удаление практики
 */
export const useDeletePractical = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePractical>>, TError,DeletePracticalMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePractical>>,
        TError,
        DeletePracticalMutationVariables,
        TContext
      > => {
      return useMutation(getDeletePracticalMutationOptions(options), queryClient);
    }
    export type getPracticalTasksResponse200 = {
  data: TaskResponse[]
  status: 200
}

export type getPracticalTasksResponse401 = {
  data: void
  status: 401
}

export type getPracticalTasksResponse403 = {
  data: void
  status: 403
}

export type getPracticalTasksResponseSuccess = (getPracticalTasksResponse200) & {
  headers: Headers;
};
export type getPracticalTasksResponseError = (getPracticalTasksResponse401 | getPracticalTasksResponse403) & {
  headers: Headers;
};

export type getPracticalTasksResponse = (getPracticalTasksResponseSuccess | getPracticalTasksResponseError)

export const getGetPracticalTasksUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/tasks`
}

/**
 * Возвращает задачи, входящие в практическое задание.
 * @summary Получение заданий практики
 */
export const getPracticalTasks = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getPracticalTasksResponse> => {

  return educationFetch<getPracticalTasksResponse>(getGetPracticalTasksUrl(practicalId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticalTasksQueryKey = (practicalId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/tasks`
    ] as const;
    }


export const getGetPracticalTasksQueryOptions = <TData = Awaited<ReturnType<typeof getPracticalTasks>>, TError = void>(practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalTasks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticalTasksQueryKey(practicalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticalTasks>>> = ({ signal }) => getPracticalTasks(practicalId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticalTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPracticalTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticalTasks>>>
export type GetPracticalTasksQueryError = void


export function useGetPracticalTasks<TData = Awaited<ReturnType<typeof getPracticalTasks>>, TError = void>(
 practicalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalTasks>>,
          TError,
          Awaited<ReturnType<typeof getPracticalTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalTasks<TData = Awaited<ReturnType<typeof getPracticalTasks>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalTasks>>,
          TError,
          Awaited<ReturnType<typeof getPracticalTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalTasks<TData = Awaited<ReturnType<typeof getPracticalTasks>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalTasks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение заданий практики
 */

export function useGetPracticalTasks<TData = Awaited<ReturnType<typeof getPracticalTasks>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalTasks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPracticalTasksQueryOptions(practicalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createPracticalTaskResponse200 = {
  data: TaskResponse
  status: 200
}

export type createPracticalTaskResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createPracticalTaskResponse401 = {
  data: void
  status: 401
}

export type createPracticalTaskResponse403 = {
  data: void
  status: 403
}

export type createPracticalTaskResponse404 = {
  data: void
  status: 404
}

export type createPracticalTaskResponseSuccess = (createPracticalTaskResponse200) & {
  headers: Headers;
};
export type createPracticalTaskResponseError = (createPracticalTaskResponse400 | createPracticalTaskResponse401 | createPracticalTaskResponse403 | createPracticalTaskResponse404) & {
  headers: Headers;
};

export type createPracticalTaskResponse = (createPracticalTaskResponseSuccess | createPracticalTaskResponseError)

export const getCreatePracticalTaskUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/tasks`
}

/**
 * Создаёт задание внутри практического материала текущего преподавателя.
 * @summary Создание задания практики
 */
export const createPracticalTask = async (practicalId: string,
    createTaskRequest: CreateTaskRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createPracticalTaskResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createPracticalTaskResponse>(getCreatePracticalTaskUrl(practicalId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTaskRequest)
  }
);}





export const getCreatePracticalTaskMutationKey = () => ['createPracticalTask'] as const;

export const getCreatePracticalTaskMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPracticalTask>>, TError,CreatePracticalTaskMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPracticalTask>>, TError,CreatePracticalTaskMutationVariables, TContext> => {

const mutationKey = getCreatePracticalTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPracticalTask>>, CreatePracticalTaskMutationVariables> = (props) => {
          const {practicalId,data} = props ?? {};

          return  createPracticalTask(practicalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePracticalTaskMutationResult = NonNullable<Awaited<ReturnType<typeof createPracticalTask>>>
    export type CreatePracticalTaskMutationBody = CreateTaskRequest
    export type CreatePracticalTaskMutationError = HttpValidationProblemDetails | void
    export type CreatePracticalTaskMutationVariables = {practicalId: string;data: CreateTaskRequest}

    /**
 * @summary Создание задания практики
 */
export const useCreatePracticalTask = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPracticalTask>>, TError,CreatePracticalTaskMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPracticalTask>>,
        TError,
        CreatePracticalTaskMutationVariables,
        TContext
      > => {
      return useMutation(getCreatePracticalTaskMutationOptions(options), queryClient);
    }
    export type updatePracticalTaskTextResponse204 = {
  data: void
  status: 204
}

export type updatePracticalTaskTextResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updatePracticalTaskTextResponse401 = {
  data: void
  status: 401
}

export type updatePracticalTaskTextResponse403 = {
  data: void
  status: 403
}

export type updatePracticalTaskTextResponse404 = {
  data: void
  status: 404
}

export type updatePracticalTaskTextResponseSuccess = (updatePracticalTaskTextResponse204) & {
  headers: Headers;
};
export type updatePracticalTaskTextResponseError = (updatePracticalTaskTextResponse400 | updatePracticalTaskTextResponse401 | updatePracticalTaskTextResponse403 | updatePracticalTaskTextResponse404) & {
  headers: Headers;
};

export type updatePracticalTaskTextResponse = (updatePracticalTaskTextResponseSuccess | updatePracticalTaskTextResponseError)

export const getUpdatePracticalTaskTextUrl = (taskId: string,) => {




  return `/api/v1/tasks/${taskId}/text`
}

/**
 * Изменяет текст задания практического материала текущего преподавателя.
 * @summary Обновление текста задания практики
 */
export const updatePracticalTaskText = async (taskId: string,
    updateTaskTextRequest: UpdateTaskTextRequest, options?: Parameters<typeof educationFetch>[1]): Promise<updatePracticalTaskTextResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<updatePracticalTaskTextResponse>(getUpdatePracticalTaskTextUrl(taskId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTaskTextRequest)
  }
);}





export const getUpdatePracticalTaskTextMutationKey = () => ['updatePracticalTaskText'] as const;

export const getUpdatePracticalTaskTextMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePracticalTaskText>>, TError,UpdatePracticalTaskTextMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePracticalTaskText>>, TError,UpdatePracticalTaskTextMutationVariables, TContext> => {

const mutationKey = getUpdatePracticalTaskTextMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePracticalTaskText>>, UpdatePracticalTaskTextMutationVariables> = (props) => {
          const {taskId,data} = props ?? {};

          return  updatePracticalTaskText(taskId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePracticalTaskTextMutationResult = NonNullable<Awaited<ReturnType<typeof updatePracticalTaskText>>>
    export type UpdatePracticalTaskTextMutationBody = UpdateTaskTextRequest
    export type UpdatePracticalTaskTextMutationError = HttpValidationProblemDetails | void
    export type UpdatePracticalTaskTextMutationVariables = {taskId: string;data: UpdateTaskTextRequest}

    /**
 * @summary Обновление текста задания практики
 */
export const useUpdatePracticalTaskText = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePracticalTaskText>>, TError,UpdatePracticalTaskTextMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePracticalTaskText>>,
        TError,
        UpdatePracticalTaskTextMutationVariables,
        TContext
      > => {
      return useMutation(getUpdatePracticalTaskTextMutationOptions(options), queryClient);
    }
    export type deletePracticalTaskResponse204 = {
  data: void
  status: 204
}

export type deletePracticalTaskResponse401 = {
  data: void
  status: 401
}

export type deletePracticalTaskResponse403 = {
  data: void
  status: 403
}

export type deletePracticalTaskResponse404 = {
  data: void
  status: 404
}

export type deletePracticalTaskResponseSuccess = (deletePracticalTaskResponse204) & {
  headers: Headers;
};
export type deletePracticalTaskResponseError = (deletePracticalTaskResponse401 | deletePracticalTaskResponse403 | deletePracticalTaskResponse404) & {
  headers: Headers;
};

export type deletePracticalTaskResponse = (deletePracticalTaskResponseSuccess | deletePracticalTaskResponseError)

export const getDeletePracticalTaskUrl = (taskId: string,) => {




  return `/api/v1/tasks/${taskId}`
}

/**
 * Удаляет задание практического материала текущего преподавателя.
 * @summary Удаление задания практики
 */
export const deletePracticalTask = async (taskId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deletePracticalTaskResponse> => {

  return educationFetch<deletePracticalTaskResponse>(getDeletePracticalTaskUrl(taskId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePracticalTaskMutationKey = () => ['deletePracticalTask'] as const;

export const getDeletePracticalTaskMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePracticalTask>>, TError,DeletePracticalTaskMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePracticalTask>>, TError,DeletePracticalTaskMutationVariables, TContext> => {

const mutationKey = getDeletePracticalTaskMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePracticalTask>>, DeletePracticalTaskMutationVariables> = (props) => {
          const {taskId} = props ?? {};

          return  deletePracticalTask(taskId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePracticalTaskMutationResult = NonNullable<Awaited<ReturnType<typeof deletePracticalTask>>>

    export type DeletePracticalTaskMutationError = void
    export type DeletePracticalTaskMutationVariables = {taskId: string}

    /**
 * @summary Удаление задания практики
 */
export const useDeletePracticalTask = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePracticalTask>>, TError,DeletePracticalTaskMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePracticalTask>>,
        TError,
        DeletePracticalTaskMutationVariables,
        TContext
      > => {
      return useMutation(getDeletePracticalTaskMutationOptions(options), queryClient);
    }
    export type getPracticalQuestionsSetupResponse200 = {
  data: PracticalQuestionsSetupResponse
  status: 200
}

export type getPracticalQuestionsSetupResponse401 = {
  data: void
  status: 401
}

export type getPracticalQuestionsSetupResponse403 = {
  data: void
  status: 403
}

export type getPracticalQuestionsSetupResponse404 = {
  data: void
  status: 404
}

export type getPracticalQuestionsSetupResponseSuccess = (getPracticalQuestionsSetupResponse200) & {
  headers: Headers;
};
export type getPracticalQuestionsSetupResponseError = (getPracticalQuestionsSetupResponse401 | getPracticalQuestionsSetupResponse403 | getPracticalQuestionsSetupResponse404) & {
  headers: Headers;
};

export type getPracticalQuestionsSetupResponse = (getPracticalQuestionsSetupResponseSuccess | getPracticalQuestionsSetupResponseError)

export const getGetPracticalQuestionsSetupUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/questions`
}

/**
 * Возвращает вопросы модуля и признак их включения в тест практики.
 * @summary Получение настройки вопросов практики
 */
export const getPracticalQuestionsSetup = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getPracticalQuestionsSetupResponse> => {

  return educationFetch<getPracticalQuestionsSetupResponse>(getGetPracticalQuestionsSetupUrl(practicalId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticalQuestionsSetupQueryKey = (practicalId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/questions`
    ] as const;
    }


export const getGetPracticalQuestionsSetupQueryOptions = <TData = Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError = void>(practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticalQuestionsSetupQueryKey(practicalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>> = ({ signal }) => getPracticalQuestionsSetup(practicalId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPracticalQuestionsSetupQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>>
export type GetPracticalQuestionsSetupQueryError = void


export function useGetPracticalQuestionsSetup<TData = Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError = void>(
 practicalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalQuestionsSetup>>,
          TError,
          Awaited<ReturnType<typeof getPracticalQuestionsSetup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalQuestionsSetup<TData = Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalQuestionsSetup>>,
          TError,
          Awaited<ReturnType<typeof getPracticalQuestionsSetup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalQuestionsSetup<TData = Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение настройки вопросов практики
 */

export function useGetPracticalQuestionsSetup<TData = Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalQuestionsSetup>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPracticalQuestionsSetupQueryOptions(practicalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type configurePracticalQuestionsResponse204 = {
  data: void
  status: 204
}

export type configurePracticalQuestionsResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type configurePracticalQuestionsResponse401 = {
  data: void
  status: 401
}

export type configurePracticalQuestionsResponse403 = {
  data: void
  status: 403
}

export type configurePracticalQuestionsResponse404 = {
  data: void
  status: 404
}

export type configurePracticalQuestionsResponseSuccess = (configurePracticalQuestionsResponse204) & {
  headers: Headers;
};
export type configurePracticalQuestionsResponseError = (configurePracticalQuestionsResponse400 | configurePracticalQuestionsResponse401 | configurePracticalQuestionsResponse403 | configurePracticalQuestionsResponse404) & {
  headers: Headers;
};

export type configurePracticalQuestionsResponse = (configurePracticalQuestionsResponseSuccess | configurePracticalQuestionsResponseError)

export const getConfigurePracticalQuestionsUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/questions`
}

/**
 * Обновляет набор вопросов, используемых в тесте практического задания.
 * @summary Настройка вопросов практики
 */
export const configurePracticalQuestions = async (practicalId: string,
    configurePracticalQuestionsRequest: ConfigurePracticalQuestionsRequest, options?: Parameters<typeof educationFetch>[1]): Promise<configurePracticalQuestionsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<configurePracticalQuestionsResponse>(getConfigurePracticalQuestionsUrl(practicalId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(configurePracticalQuestionsRequest)
  }
);}





export const getConfigurePracticalQuestionsMutationKey = () => ['configurePracticalQuestions'] as const;

export const getConfigurePracticalQuestionsMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configurePracticalQuestions>>, TError,ConfigurePracticalQuestionsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof configurePracticalQuestions>>, TError,ConfigurePracticalQuestionsMutationVariables, TContext> => {

const mutationKey = getConfigurePracticalQuestionsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof configurePracticalQuestions>>, ConfigurePracticalQuestionsMutationVariables> = (props) => {
          const {practicalId,data} = props ?? {};

          return  configurePracticalQuestions(practicalId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConfigurePracticalQuestionsMutationResult = NonNullable<Awaited<ReturnType<typeof configurePracticalQuestions>>>
    export type ConfigurePracticalQuestionsMutationBody = ConfigurePracticalQuestionsRequest
    export type ConfigurePracticalQuestionsMutationError = HttpValidationProblemDetails | void
    export type ConfigurePracticalQuestionsMutationVariables = {practicalId: string;data: ConfigurePracticalQuestionsRequest}

    /**
 * @summary Настройка вопросов практики
 */
export const useConfigurePracticalQuestions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof configurePracticalQuestions>>, TError,ConfigurePracticalQuestionsMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof configurePracticalQuestions>>,
        TError,
        ConfigurePracticalQuestionsMutationVariables,
        TContext
      > => {
      return useMutation(getConfigurePracticalQuestionsMutationOptions(options), queryClient);
    }
