/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTheoryDocumentBody,
  CreateTheoryLinkRequest,
  CreateTheoryRequest,
  HttpValidationProblemDetails,
  ProblemDetails,
  TheoryDocumentResponse,
  TheoryLinkResponse,
  TheoryListItemResponse,
  TheoryTextResponse,
  UpdateTheoryTextRequest,
  UpdateTheoryTitleRequest
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getTheoryResponse200 = {
  data: TheoryTextResponse
  status: 200
}

export type getTheoryResponse401 = {
  data: void
  status: 401
}

export type getTheoryResponse403 = {
  data: void
  status: 403
}

export type getTheoryResponse404 = {
  data: void
  status: 404
}

export type getTheoryResponseSuccess = (getTheoryResponse200) & {
  headers: Headers;
};
export type getTheoryResponseError = (getTheoryResponse401 | getTheoryResponse403 | getTheoryResponse404) & {
  headers: Headers;
};

export type getTheoryResponse = (getTheoryResponseSuccess | getTheoryResponseError)

export const getGetTheoryUrl = (theoryId: string,) => {




  return `/api/v1/theories/${theoryId}`
}

/**
 * Возвращает заголовок и текст теоретического материала.
 * @summary Получение текста теории
 */
export const getTheory = async (theoryId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getTheoryResponse> => {

  return educationFetch<getTheoryResponse>(getGetTheoryUrl(theoryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTheoryQueryKey = (theoryId: string,) => {
    return [
    `/api/v1/theories/${theoryId}`
    ] as const;
    }


export const getGetTheoryQueryOptions = <TData = Awaited<ReturnType<typeof getTheory>>, TError = void>(theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheory>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTheoryQueryKey(theoryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTheory>>> = ({ signal }) => getTheory(theoryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: theoryId !== null && theoryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTheory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTheoryQueryResult = NonNullable<Awaited<ReturnType<typeof getTheory>>>
export type GetTheoryQueryError = void


export function useGetTheory<TData = Awaited<ReturnType<typeof getTheory>>, TError = void>(
 theoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheory>>,
          TError,
          Awaited<ReturnType<typeof getTheory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheory<TData = Awaited<ReturnType<typeof getTheory>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheory>>,
          TError,
          Awaited<ReturnType<typeof getTheory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheory<TData = Awaited<ReturnType<typeof getTheory>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheory>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение текста теории
 */

export function useGetTheory<TData = Awaited<ReturnType<typeof getTheory>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheory>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTheoryQueryOptions(theoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteTheoryResponse204 = {
  data: void
  status: 204
}

export type deleteTheoryResponse401 = {
  data: void
  status: 401
}

export type deleteTheoryResponse403 = {
  data: void
  status: 403
}

export type deleteTheoryResponse404 = {
  data: void
  status: 404
}

export type deleteTheoryResponseSuccess = (deleteTheoryResponse204) & {
  headers: Headers;
};
export type deleteTheoryResponseError = (deleteTheoryResponse401 | deleteTheoryResponse403 | deleteTheoryResponse404) & {
  headers: Headers;
};

export type deleteTheoryResponse = (deleteTheoryResponseSuccess | deleteTheoryResponseError)

export const getDeleteTheoryUrl = (theoryId: string,) => {




  return `/api/v1/theories/${theoryId}`
}

/**
 * Удаляет теоретический материал преподавателя.
 * @summary Удаление теоретического материала
 */
export const deleteTheory = async (theoryId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deleteTheoryResponse> => {

  return educationFetch<deleteTheoryResponse>(getDeleteTheoryUrl(theoryId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTheoryMutationKey = () => ['deleteTheory'] as const;

export const getDeleteTheoryMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTheory>>, TError,DeleteTheoryMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTheory>>, TError,DeleteTheoryMutationVariables, TContext> => {

const mutationKey = getDeleteTheoryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTheory>>, DeleteTheoryMutationVariables> = (props) => {
          const {theoryId} = props ?? {};

          return  deleteTheory(theoryId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTheoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTheory>>>

    export type DeleteTheoryMutationError = void
    export type DeleteTheoryMutationVariables = {theoryId: string}

    /**
 * @summary Удаление теоретического материала
 */
export const useDeleteTheory = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTheory>>, TError,DeleteTheoryMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTheory>>,
        TError,
        DeleteTheoryMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteTheoryMutationOptions(options), queryClient);
    }
    export type getTheoryDocumentsResponse200 = {
  data: TheoryDocumentResponse[]
  status: 200
}

export type getTheoryDocumentsResponse401 = {
  data: void
  status: 401
}

export type getTheoryDocumentsResponse403 = {
  data: void
  status: 403
}

export type getTheoryDocumentsResponseSuccess = (getTheoryDocumentsResponse200) & {
  headers: Headers;
};
export type getTheoryDocumentsResponseError = (getTheoryDocumentsResponse401 | getTheoryDocumentsResponse403) & {
  headers: Headers;
};

export type getTheoryDocumentsResponse = (getTheoryDocumentsResponseSuccess | getTheoryDocumentsResponseError)

export const getGetTheoryDocumentsUrl = (theoryId: string,) => {




  return `/api/v1/theories/${theoryId}/docs`
}

/**
 * Возвращает документы, прикреплённые к теоретическому материалу.
 * @summary Получение документов теории
 */
export const getTheoryDocuments = async (theoryId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getTheoryDocumentsResponse> => {

  return educationFetch<getTheoryDocumentsResponse>(getGetTheoryDocumentsUrl(theoryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTheoryDocumentsQueryKey = (theoryId: string,) => {
    return [
    `/api/v1/theories/${theoryId}/docs`
    ] as const;
    }


export const getGetTheoryDocumentsQueryOptions = <TData = Awaited<ReturnType<typeof getTheoryDocuments>>, TError = void>(theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryDocuments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTheoryDocumentsQueryKey(theoryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTheoryDocuments>>> = ({ signal }) => getTheoryDocuments(theoryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: theoryId !== null && theoryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTheoryDocuments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTheoryDocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof getTheoryDocuments>>>
export type GetTheoryDocumentsQueryError = void


export function useGetTheoryDocuments<TData = Awaited<ReturnType<typeof getTheoryDocuments>>, TError = void>(
 theoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryDocuments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheoryDocuments>>,
          TError,
          Awaited<ReturnType<typeof getTheoryDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheoryDocuments<TData = Awaited<ReturnType<typeof getTheoryDocuments>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryDocuments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheoryDocuments>>,
          TError,
          Awaited<ReturnType<typeof getTheoryDocuments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheoryDocuments<TData = Awaited<ReturnType<typeof getTheoryDocuments>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryDocuments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение документов теории
 */

export function useGetTheoryDocuments<TData = Awaited<ReturnType<typeof getTheoryDocuments>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryDocuments>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTheoryDocumentsQueryOptions(theoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getTheoryLinksResponse200 = {
  data: TheoryLinkResponse[]
  status: 200
}

export type getTheoryLinksResponse401 = {
  data: void
  status: 401
}

export type getTheoryLinksResponse403 = {
  data: void
  status: 403
}

export type getTheoryLinksResponseSuccess = (getTheoryLinksResponse200) & {
  headers: Headers;
};
export type getTheoryLinksResponseError = (getTheoryLinksResponse401 | getTheoryLinksResponse403) & {
  headers: Headers;
};

export type getTheoryLinksResponse = (getTheoryLinksResponseSuccess | getTheoryLinksResponseError)

export const getGetTheoryLinksUrl = (theoryId: string,) => {




  return `/api/v1/theories/${theoryId}/links`
}

/**
 * Возвращает внешние ссылки, прикреплённые к теоретическому материалу.
 * @summary Получение ссылок теории
 */
export const getTheoryLinks = async (theoryId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getTheoryLinksResponse> => {

  return educationFetch<getTheoryLinksResponse>(getGetTheoryLinksUrl(theoryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTheoryLinksQueryKey = (theoryId: string,) => {
    return [
    `/api/v1/theories/${theoryId}/links`
    ] as const;
    }


export const getGetTheoryLinksQueryOptions = <TData = Awaited<ReturnType<typeof getTheoryLinks>>, TError = void>(theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryLinks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTheoryLinksQueryKey(theoryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTheoryLinks>>> = ({ signal }) => getTheoryLinks(theoryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: theoryId !== null && theoryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTheoryLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTheoryLinksQueryResult = NonNullable<Awaited<ReturnType<typeof getTheoryLinks>>>
export type GetTheoryLinksQueryError = void


export function useGetTheoryLinks<TData = Awaited<ReturnType<typeof getTheoryLinks>>, TError = void>(
 theoryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheoryLinks>>,
          TError,
          Awaited<ReturnType<typeof getTheoryLinks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheoryLinks<TData = Awaited<ReturnType<typeof getTheoryLinks>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheoryLinks>>,
          TError,
          Awaited<ReturnType<typeof getTheoryLinks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheoryLinks<TData = Awaited<ReturnType<typeof getTheoryLinks>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryLinks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение ссылок теории
 */

export function useGetTheoryLinks<TData = Awaited<ReturnType<typeof getTheoryLinks>>, TError = void>(
 theoryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheoryLinks>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTheoryLinksQueryOptions(theoryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createTheoryResponse200 = {
  data: TheoryListItemResponse
  status: 200
}

export type createTheoryResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createTheoryResponse401 = {
  data: void
  status: 401
}

export type createTheoryResponse403 = {
  data: void
  status: 403
}

export type createTheoryResponse404 = {
  data: void
  status: 404
}

export type createTheoryResponseSuccess = (createTheoryResponse200) & {
  headers: Headers;
};
export type createTheoryResponseError = (createTheoryResponse400 | createTheoryResponse401 | createTheoryResponse403 | createTheoryResponse404) & {
  headers: Headers;
};

export type createTheoryResponse = (createTheoryResponseSuccess | createTheoryResponseError)

export const getCreateTheoryUrl = () => {




  return `/api/v1/theories`
}

/**
 * Создаёт теоретический материал внутри модуля преподавателя.
 * @summary Создание теоретического материала
 */
export const createTheory = async (createTheoryRequest: CreateTheoryRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createTheoryResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createTheoryResponse>(getCreateTheoryUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTheoryRequest)
  }
);}





export const getCreateTheoryMutationKey = () => ['createTheory'] as const;

export const getCreateTheoryMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTheory>>, TError,CreateTheoryMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createTheory>>, TError,CreateTheoryMutationVariables, TContext> => {

const mutationKey = getCreateTheoryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTheory>>, CreateTheoryMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTheory(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTheoryMutationResult = NonNullable<Awaited<ReturnType<typeof createTheory>>>
    export type CreateTheoryMutationBody = CreateTheoryRequest
    export type CreateTheoryMutationError = HttpValidationProblemDetails | void
    export type CreateTheoryMutationVariables = {data: CreateTheoryRequest}

    /**
 * @summary Создание теоретического материала
 */
export const useCreateTheory = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTheory>>, TError,CreateTheoryMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTheory>>,
        TError,
        CreateTheoryMutationVariables,
        TContext
      > => {
      return useMutation(getCreateTheoryMutationOptions(options), queryClient);
    }
    export type updateTheoryTitleResponse204 = {
  data: void
  status: 204
}

export type updateTheoryTitleResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateTheoryTitleResponse401 = {
  data: void
  status: 401
}

export type updateTheoryTitleResponse403 = {
  data: void
  status: 403
}

export type updateTheoryTitleResponse404 = {
  data: void
  status: 404
}

export type updateTheoryTitleResponseSuccess = (updateTheoryTitleResponse204) & {
  headers: Headers;
};
export type updateTheoryTitleResponseError = (updateTheoryTitleResponse400 | updateTheoryTitleResponse401 | updateTheoryTitleResponse403 | updateTheoryTitleResponse404) & {
  headers: Headers;
};

export type updateTheoryTitleResponse = (updateTheoryTitleResponseSuccess | updateTheoryTitleResponseError)

export const getUpdateTheoryTitleUrl = (theoryId: string,) => {




  return `/api/v1/theories/${theoryId}/title`
}

/**
 * Изменяет название теоретического материала.
 * @summary Обновление заголовка теории
 */
export const updateTheoryTitle = async (theoryId: string,
    updateTheoryTitleRequest: UpdateTheoryTitleRequest, options?: Parameters<typeof educationFetch>[1]): Promise<updateTheoryTitleResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<updateTheoryTitleResponse>(getUpdateTheoryTitleUrl(theoryId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTheoryTitleRequest)
  }
);}





export const getUpdateTheoryTitleMutationKey = () => ['updateTheoryTitle'] as const;

export const getUpdateTheoryTitleMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTheoryTitle>>, TError,UpdateTheoryTitleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTheoryTitle>>, TError,UpdateTheoryTitleMutationVariables, TContext> => {

const mutationKey = getUpdateTheoryTitleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTheoryTitle>>, UpdateTheoryTitleMutationVariables> = (props) => {
          const {theoryId,data} = props ?? {};

          return  updateTheoryTitle(theoryId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTheoryTitleMutationResult = NonNullable<Awaited<ReturnType<typeof updateTheoryTitle>>>
    export type UpdateTheoryTitleMutationBody = UpdateTheoryTitleRequest
    export type UpdateTheoryTitleMutationError = HttpValidationProblemDetails | void
    export type UpdateTheoryTitleMutationVariables = {theoryId: string;data: UpdateTheoryTitleRequest}

    /**
 * @summary Обновление заголовка теории
 */
export const useUpdateTheoryTitle = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTheoryTitle>>, TError,UpdateTheoryTitleMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTheoryTitle>>,
        TError,
        UpdateTheoryTitleMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateTheoryTitleMutationOptions(options), queryClient);
    }
    export type updateTheoryTextResponse204 = {
  data: void
  status: 204
}

export type updateTheoryTextResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateTheoryTextResponse401 = {
  data: void
  status: 401
}

export type updateTheoryTextResponse403 = {
  data: void
  status: 403
}

export type updateTheoryTextResponse404 = {
  data: void
  status: 404
}

export type updateTheoryTextResponseSuccess = (updateTheoryTextResponse204) & {
  headers: Headers;
};
export type updateTheoryTextResponseError = (updateTheoryTextResponse400 | updateTheoryTextResponse401 | updateTheoryTextResponse403 | updateTheoryTextResponse404) & {
  headers: Headers;
};

export type updateTheoryTextResponse = (updateTheoryTextResponseSuccess | updateTheoryTextResponseError)

export const getUpdateTheoryTextUrl = (theoryId: string,) => {




  return `/api/v1/theories/${theoryId}/text`
}

/**
 * Изменяет текст теоретического материала.
 * @summary Обновление текста теории
 */
export const updateTheoryText = async (theoryId: string,
    updateTheoryTextRequest: UpdateTheoryTextRequest, options?: Parameters<typeof educationFetch>[1]): Promise<updateTheoryTextResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<updateTheoryTextResponse>(getUpdateTheoryTextUrl(theoryId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTheoryTextRequest)
  }
);}





export const getUpdateTheoryTextMutationKey = () => ['updateTheoryText'] as const;

export const getUpdateTheoryTextMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTheoryText>>, TError,UpdateTheoryTextMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTheoryText>>, TError,UpdateTheoryTextMutationVariables, TContext> => {

const mutationKey = getUpdateTheoryTextMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTheoryText>>, UpdateTheoryTextMutationVariables> = (props) => {
          const {theoryId,data} = props ?? {};

          return  updateTheoryText(theoryId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTheoryTextMutationResult = NonNullable<Awaited<ReturnType<typeof updateTheoryText>>>
    export type UpdateTheoryTextMutationBody = UpdateTheoryTextRequest
    export type UpdateTheoryTextMutationError = HttpValidationProblemDetails | void
    export type UpdateTheoryTextMutationVariables = {theoryId: string;data: UpdateTheoryTextRequest}

    /**
 * @summary Обновление текста теории
 */
export const useUpdateTheoryText = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTheoryText>>, TError,UpdateTheoryTextMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTheoryText>>,
        TError,
        UpdateTheoryTextMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateTheoryTextMutationOptions(options), queryClient);
    }
    export type createTheoryDocumentResponse200 = {
  data: TheoryDocumentResponse
  status: 200
}

export type createTheoryDocumentResponse400 = {
  data: ProblemDetails
  status: 400
}

export type createTheoryDocumentResponse401 = {
  data: void
  status: 401
}

export type createTheoryDocumentResponse403 = {
  data: void
  status: 403
}

export type createTheoryDocumentResponse404 = {
  data: void
  status: 404
}

export type createTheoryDocumentResponseSuccess = (createTheoryDocumentResponse200) & {
  headers: Headers;
};
export type createTheoryDocumentResponseError = (createTheoryDocumentResponse400 | createTheoryDocumentResponse401 | createTheoryDocumentResponse403 | createTheoryDocumentResponse404) & {
  headers: Headers;
};

export type createTheoryDocumentResponse = (createTheoryDocumentResponseSuccess | createTheoryDocumentResponseError)

export const getCreateTheoryDocumentUrl = () => {




  return `/api/v1/theories/docs`
}

/**
 * Добавляет документ к теоретическому материалу преподавателя.
 * @summary Загрузка документа теории
 */
export const createTheoryDocument = async (createTheoryDocumentBody: CreateTheoryDocumentBody, options?: Parameters<typeof educationFetch>[1]): Promise<createTheoryDocumentResponse> => {
    const formData = new FormData();
if(createTheoryDocumentBody.theoryMaterialId !== undefined) {
 formData.append(`theoryMaterialId`, createTheoryDocumentBody.theoryMaterialId);
 }

if(createTheoryDocumentBody.descritpion !== undefined) {
 formData.append(`descritpion`, createTheoryDocumentBody.descritpion);
 }

if(createTheoryDocumentBody.description !== undefined) {
 formData.append(`description`, createTheoryDocumentBody.description);
 }

if(createTheoryDocumentBody.file !== undefined) {
 formData.append(`file`, createTheoryDocumentBody.file);
 }

  return educationFetch<createTheoryDocumentResponse>(getCreateTheoryDocumentUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getCreateTheoryDocumentMutationKey = () => ['createTheoryDocument'] as const;

export const getCreateTheoryDocumentMutationOptions = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTheoryDocument>>, TError,CreateTheoryDocumentMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createTheoryDocument>>, TError,CreateTheoryDocumentMutationVariables, TContext> => {

const mutationKey = getCreateTheoryDocumentMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTheoryDocument>>, CreateTheoryDocumentMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTheoryDocument(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTheoryDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof createTheoryDocument>>>
    export type CreateTheoryDocumentMutationBody = CreateTheoryDocumentBody
    export type CreateTheoryDocumentMutationError = ProblemDetails | void
    export type CreateTheoryDocumentMutationVariables = {data: CreateTheoryDocumentBody}

    /**
 * @summary Загрузка документа теории
 */
export const useCreateTheoryDocument = <TError = ProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTheoryDocument>>, TError,CreateTheoryDocumentMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTheoryDocument>>,
        TError,
        CreateTheoryDocumentMutationVariables,
        TContext
      > => {
      return useMutation(getCreateTheoryDocumentMutationOptions(options), queryClient);
    }
    export type deleteTheoryDocumentResponse204 = {
  data: void
  status: 204
}

export type deleteTheoryDocumentResponse401 = {
  data: void
  status: 401
}

export type deleteTheoryDocumentResponse403 = {
  data: void
  status: 403
}

export type deleteTheoryDocumentResponse404 = {
  data: void
  status: 404
}

export type deleteTheoryDocumentResponseSuccess = (deleteTheoryDocumentResponse204) & {
  headers: Headers;
};
export type deleteTheoryDocumentResponseError = (deleteTheoryDocumentResponse401 | deleteTheoryDocumentResponse403 | deleteTheoryDocumentResponse404) & {
  headers: Headers;
};

export type deleteTheoryDocumentResponse = (deleteTheoryDocumentResponseSuccess | deleteTheoryDocumentResponseError)

export const getDeleteTheoryDocumentUrl = (docId: string,) => {




  return `/api/v1/theories/docs/${docId}`
}

/**
 * Удаляет документ теоретического материала преподавателя.
 * @summary Удаление документа теории
 */
export const deleteTheoryDocument = async (docId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deleteTheoryDocumentResponse> => {

  return educationFetch<deleteTheoryDocumentResponse>(getDeleteTheoryDocumentUrl(docId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTheoryDocumentMutationKey = () => ['deleteTheoryDocument'] as const;

export const getDeleteTheoryDocumentMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTheoryDocument>>, TError,DeleteTheoryDocumentMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTheoryDocument>>, TError,DeleteTheoryDocumentMutationVariables, TContext> => {

const mutationKey = getDeleteTheoryDocumentMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTheoryDocument>>, DeleteTheoryDocumentMutationVariables> = (props) => {
          const {docId} = props ?? {};

          return  deleteTheoryDocument(docId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTheoryDocumentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTheoryDocument>>>

    export type DeleteTheoryDocumentMutationError = void
    export type DeleteTheoryDocumentMutationVariables = {docId: string}

    /**
 * @summary Удаление документа теории
 */
export const useDeleteTheoryDocument = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTheoryDocument>>, TError,DeleteTheoryDocumentMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTheoryDocument>>,
        TError,
        DeleteTheoryDocumentMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteTheoryDocumentMutationOptions(options), queryClient);
    }
    export type createTheoryLinkResponse200 = {
  data: TheoryLinkResponse
  status: 200
}

export type createTheoryLinkResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createTheoryLinkResponse401 = {
  data: void
  status: 401
}

export type createTheoryLinkResponse403 = {
  data: void
  status: 403
}

export type createTheoryLinkResponse404 = {
  data: void
  status: 404
}

export type createTheoryLinkResponseSuccess = (createTheoryLinkResponse200) & {
  headers: Headers;
};
export type createTheoryLinkResponseError = (createTheoryLinkResponse400 | createTheoryLinkResponse401 | createTheoryLinkResponse403 | createTheoryLinkResponse404) & {
  headers: Headers;
};

export type createTheoryLinkResponse = (createTheoryLinkResponseSuccess | createTheoryLinkResponseError)

export const getCreateTheoryLinkUrl = () => {




  return `/api/v1/theories/links`
}

/**
 * Добавляет внешнюю ссылку к теоретическому материалу преподавателя.
 * @summary Создание ссылки теории
 */
export const createTheoryLink = async (createTheoryLinkRequest: CreateTheoryLinkRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createTheoryLinkResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createTheoryLinkResponse>(getCreateTheoryLinkUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTheoryLinkRequest)
  }
);}





export const getCreateTheoryLinkMutationKey = () => ['createTheoryLink'] as const;

export const getCreateTheoryLinkMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTheoryLink>>, TError,CreateTheoryLinkMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createTheoryLink>>, TError,CreateTheoryLinkMutationVariables, TContext> => {

const mutationKey = getCreateTheoryLinkMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTheoryLink>>, CreateTheoryLinkMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTheoryLink(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTheoryLinkMutationResult = NonNullable<Awaited<ReturnType<typeof createTheoryLink>>>
    export type CreateTheoryLinkMutationBody = CreateTheoryLinkRequest
    export type CreateTheoryLinkMutationError = HttpValidationProblemDetails | void
    export type CreateTheoryLinkMutationVariables = {data: CreateTheoryLinkRequest}

    /**
 * @summary Создание ссылки теории
 */
export const useCreateTheoryLink = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTheoryLink>>, TError,CreateTheoryLinkMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTheoryLink>>,
        TError,
        CreateTheoryLinkMutationVariables,
        TContext
      > => {
      return useMutation(getCreateTheoryLinkMutationOptions(options), queryClient);
    }
    export type deleteTheoryLinkResponse204 = {
  data: void
  status: 204
}

export type deleteTheoryLinkResponse401 = {
  data: void
  status: 401
}

export type deleteTheoryLinkResponse403 = {
  data: void
  status: 403
}

export type deleteTheoryLinkResponse404 = {
  data: void
  status: 404
}

export type deleteTheoryLinkResponseSuccess = (deleteTheoryLinkResponse204) & {
  headers: Headers;
};
export type deleteTheoryLinkResponseError = (deleteTheoryLinkResponse401 | deleteTheoryLinkResponse403 | deleteTheoryLinkResponse404) & {
  headers: Headers;
};

export type deleteTheoryLinkResponse = (deleteTheoryLinkResponseSuccess | deleteTheoryLinkResponseError)

export const getDeleteTheoryLinkUrl = (linkId: string,) => {




  return `/api/v1/theories/links/${linkId}`
}

/**
 * Удаляет внешнюю ссылку теоретического материала преподавателя.
 * @summary Удаление ссылки теории
 */
export const deleteTheoryLink = async (linkId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deleteTheoryLinkResponse> => {

  return educationFetch<deleteTheoryLinkResponse>(getDeleteTheoryLinkUrl(linkId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTheoryLinkMutationKey = () => ['deleteTheoryLink'] as const;

export const getDeleteTheoryLinkMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTheoryLink>>, TError,DeleteTheoryLinkMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTheoryLink>>, TError,DeleteTheoryLinkMutationVariables, TContext> => {

const mutationKey = getDeleteTheoryLinkMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTheoryLink>>, DeleteTheoryLinkMutationVariables> = (props) => {
          const {linkId} = props ?? {};

          return  deleteTheoryLink(linkId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTheoryLinkMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTheoryLink>>>

    export type DeleteTheoryLinkMutationError = void
    export type DeleteTheoryLinkMutationVariables = {linkId: string}

    /**
 * @summary Удаление ссылки теории
 */
export const useDeleteTheoryLink = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTheoryLink>>, TError,DeleteTheoryLinkMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTheoryLink>>,
        TError,
        DeleteTheoryLinkMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteTheoryLinkMutationOptions(options), queryClient);
    }
