/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на принятие файла сдачи и выставление оценки.
 */
export interface AcceptTaskFileRequest {
  /**
     * Оценка за сдачу.
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  grade: number | string;
}
