/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на добавление комментария преподавателя к файлу сдачи.
 */
export interface AddTaskFileCommentRequest {
  /** Текст комментария. */
  comment: string;
}
