/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Локальный учебный профиль пользователя.
 */
export interface AdminProfileResponse {
  /** Идентификатор пользователя в учебной системе. */
  legacyUserId: string;
  /**
     * Идентификатор пользователя во внешнем identity-сервисе.
     * @nullable
     */
  identityUserId: string | null;
  /** Отображаемый логин или имя пользователя. */
  login: string;
  /** Имя пользователя. */
  firstName: string;
  /** Фамилия пользователя. */
  lastName: string;
  /** Отчество пользователя. */
  middleName: string;
  /** Признак активной связи с identity-сервисом. */
  isActive: boolean;
}
