/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Студент, доступный для назначения на курс или практический материал.
 */
export interface AssignableStudentResponse {
  /** Идентификатор пользователя в учебной системе. */
  legacyUserId: string;
  /** Полное имя пользователя. */
  fullName: string;
  /** Признак текущего назначения. */
  isAssigned: boolean;
}
