/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные текущего пользователя, полученные из JWT-токена.
 */
export interface AuthMeResponse {
  /** Идентификатор пользователя во внешнем identity-сервисе. */
  userId: string;
  /**
     * Адрес электронной почты пользователя из токена.
     * @nullable
     */
  email: string | null;
  /**
     * Отображаемое имя пользователя из токена.
     * @nullable
     */
  name: string | null;
  /** Роли пользователя из токена. */
  roles: string[];
  /** Признак успешной аутентификации пользователя. */
  isAuthenticated: boolean;
}
