/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос привязки внешнего модуля к практике.
 */
export interface BindPracticalModuleRequest {
  practicalModuleId: string;
  externalTaskRef: string;
  triesCount: number;
  /** @nullable */
  timeLimitMinutes: number | null;
}
