/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос привязки внешнего модуля к практике.
 */
export interface BindPracticalModuleRequest {
  practicalModuleId: string;
  externalTaskRef: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  triesCount: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  timeLimitMinutes: number | string | null;
}
