/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JsonElement } from './jsonElement';

/**
 * Тело приёма оценки от модуля (заголовок `X-Service-Key` — вне тела).
 */
export interface CompleteModuleSessionRequest {
  sessionKey: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  grade: number | string;
  completionData: null | JsonElement;
  completedAt: string;
}
