/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на настройку вопросов и порогов оценивания практического материала.
 */
export interface ConfigurePracticalQuestionsRequest {
  questionIds: string[];
  triesCount: number;
  percentForFive: number;
  percentForFour: number;
  percentForThree: number;
}
