/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные курса, возвращаемые API системы обучения.
 */
export interface CourseResponse {
  id: string;
  date: string;
  description: string;
  name: string;
}
