/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileRole } from './profileRole';

/**
 * Запрос на создание локального учебного профиля и связи с identity-пользователем.
 */
export interface CreateAdminProfileRequest {
  /** Идентификатор пользователя во внешнем identity-сервисе. */
  identityUserId: string;
  /** Отображаемый логин или имя пользователя. */
  login: string;
  /** Имя пользователя. */
  firstName: string;
  /** Фамилия пользователя. */
  lastName: string;
  /** Отчество пользователя. */
  middleName: string;
  /** Роль профиля (по умолчанию — студент). */
  role?: ProfileRole;
}
