/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на создание вопроса тестирования.
 */
export interface CreateQuestionRequest {
  moduleId: string;
  type: string;
  text: string;
  body: string;
  answer: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  weight: number | string;
}
