/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на создание курса, принадлежащего преподавателю.
 */
export interface CreateCourseRequest {
  date: string;
  description: string;
  name: string;
}
