/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на добавление внешней ссылки к теоретическому материалу.
 */
export interface CreateTheoryLinkRequest {
  theoryMaterialId: string;
  link: string;
  description: string;
}
