/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Необязательные параметры перехода преподавателя в контур авторинга внешнего модуля.
 * Тело запроса можно не передавать — тогда модуль откроется на своей стартовой странице
 * без кнопки возврата на платформу.
 */
export interface CreateModuleAuthoringLinkRequest {
  /**
     * Путь на платформе, куда модуль вернёт преподавателя: относительный, начинается с
     * одного «/» (например, `/teacher/courses/…/practicals/…`). Абсолютные адреса запрещены.
     * @nullable
     */
  returnPath: string | null;
  /**
     * Ссылка на задание модуля (`externalTaskRef`), которое нужно открыть сразу;
     * допустимы латиница, цифры, «-» и «_».
     * @nullable
     */
  taskRef: string | null;
}
