/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на создание модуля внутри курса.
 */
export interface CreateModuleRequest {
  courseId: string;
  name: string;
}
