/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на регистрацию нового практического модуля.
 */
export interface CreatePracticalModuleRequest {
  slug: string;
  name: string;
  description: string;
  practiceType: string;
  basePath: string;
  identityAudience: string;
  /** @nullable */
  configuration: string | null;
}
