/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from './iFormFile';

export type CreateTheoryDocumentBody = {
  theoryMaterialId?: string;
} & {
  descritpion?: string;
} & {
  description?: string;
} & {
  file?: IFormFile;
} & Required<Pick<{
  theoryMaterialId?: string;
} & {
  descritpion?: string;
} & {
  description?: string;
} & {
  file?: IFormFile;
}, 'theoryMaterialId' | 'file'>>;
