/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на создание теоретического материала внутри модуля.
 */
export interface CreateTheoryRequest {
  moduleId: string;
  name: string;
}
