/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ModuleSessionResponse } from './moduleSessionResponse';

/**
 * Данные гейта кнопок «Начать»/«Продолжить»/«Прервать».
 */
export interface CurrentModuleSessionResponse {
  session: null | ModuleSessionResponse;
  attemptsCount: number;
  triesCount: number;
  /** @nullable */
  timeLimitMinutes: number | null;
  /** @nullable */
  bestGrade: number | null;
}
