/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ModuleSessionResponse } from './moduleSessionResponse';

/**
 * Данные гейта кнопок «Начать»/«Продолжить»/«Прервать».
 */
export interface CurrentModuleSessionResponse {
  session: null | ModuleSessionResponse;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  attemptsCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  triesCount: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  timeLimitMinutes: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  bestGrade: number | string | null;
}
