/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Привязка внешней практики к заданию модуля.
 */
export interface ExternalModuleBindingResponse {
  practicalModuleId: string;
  practicalModuleSlug: string;
  practicalModuleName: string;
  taskId: string;
  externalTaskRef: string;
}
