/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetCourseStudentAssignmentsParams = {
search?: string;
assigned?: boolean;
group?: string;
page?: number;
pageSize?: number;
};
