/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

export * from './acceptTaskFileRequest';
export * from './addTaskFileCommentRequest';
export * from './adminProfileResponse';
export * from './assignableStudentResponse';
export * from './authMeResponse';
export * from './configurePracticalQuestionsRequest';
export * from './courseResponse';
export * from './createAdminProfileRequest';
export * from './createCourseRequest';
export * from './createModuleRequest';
export * from './createPracticalRequest';
export * from './createQuestionRequest';
export * from './createTaskRequest';
export * from './createTheoryDocumentBody';
export * from './createTheoryLinkRequest';
export * from './createTheoryRequest';
export * from './httpValidationProblemDetails';
export * from './httpValidationProblemDetailsErrors';
export * from './iFormFile';
export * from './moduleResponse';
export * from './practicalGradeResponse';
export * from './practicalQuestionsSetupResponse';
export * from './practicalResponse';
export * from './problemDetails';
export * from './questionResponse';
export * from './selectableQuestionResponse';
export * from './startTestResponse';
export * from './submitAnswerRequest';
export * from './submitTestRequest';
export * from './taskFileCommentResponse';
export * from './taskFileResponse';
export * from './taskResponse';
export * from './testProtocolAnswerResponse';
export * from './testProtocolResponse';
export * from './testProtocolSummaryResponse';
export * from './testQuestionResponse';
export * from './testQuestionsResponse';
export * from './testStatusResponse';
export * from './theoryDocumentResponse';
export * from './theoryLinkResponse';
export * from './theoryListItemResponse';
export * from './theoryTextResponse';
export * from './updateAdminProfileRequest';
export * from './updateCourseStudentsRequest';
export * from './updatePracticalStudentsRequest';
export * from './updateQuestionRequest';
export * from './updateTaskTextRequest';
export * from './updateTheoryTextRequest';
export * from './updateTheoryTitleRequest';
export * from './uploadStudentTaskFileBody';
