/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Ссылка для SSO-перехода преподавателя в контур авторинга внешнего модуля.
 * string ModuleAuthoringLinkResponse.Url открывается в текущей вкладке; int ModuleAuthoringLinkResponse.ExpiresInSeconds —
 * сколько ещё живёт вложенный в него токен.
 */
export interface ModuleAuthoringLinkResponse {
  url: string;
  expiresInSeconds: number;
}
