/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Строка списка попыток внешнего модуля для преподавателя.
 */
export interface ModuleSessionSummaryResponse {
  sessionId: string;
  userId: string;
  studentName: string;
  tryNumber: number;
  status: string;
  /** @nullable */
  endReason: string | null;
  /** @nullable */
  grade: number | null;
  startedAt: string;
  /** @nullable */
  endedAt: string | null;
}
