/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Задание из каталога внешнего практического модуля.
 */
export interface ModuleTaskResponse {
  ref: string;
  name: string;
  description: string;
}
