/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Статус попытки внешнего модуля.
 */
export interface ModuleSessionResponse {
  sessionId: string;
  status: string;
  tryNumber: number;
  startedAt: string;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  endReason: string | null;
  /** @nullable */
  grade: number | null;
  /** @nullable */
  endedAt: string | null;
}
