/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JsonElement } from './jsonElement';

/**
 * Одно событие ленты «цифрового следа» попытки.
 */
export interface ModuleSessionEventResponse {
  eventId: string;
  kind: string;
  occurredAt: string;
  payload: JsonElement;
}
