/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Статус попытки внешнего модуля.
 */
export interface ModuleSessionResponse {
  sessionId: string;
  status: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  tryNumber: number | string;
  startedAt: string;
  /** @nullable */
  expiresAt: string | null;
  /** @nullable */
  endReason: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  grade: number | string | null;
  /** @nullable */
  endedAt: string | null;
}
