/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Итоговая оценка за практический материал или список условий для её получения.
 */
export interface PracticalGradeResponse {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  grade: number | string | null;
  messages: string[];
}
