/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SelectableQuestionResponse } from './selectableQuestionResponse';

/**
 * Данные для настройки теста практического материала.
 */
export interface PracticalQuestionsSetupResponse {
  questions: SelectableQuestionResponse[];
  isPublic: boolean;
  triesCount: number;
  percentForFive: number;
  percentForFour: number;
  percentForThree: number;
}
