/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные практического материала, возвращаемые API системы обучения.
 */
export interface PracticalResponse {
  id: string;
  name: string;
}
