/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запись реестра внешнего практического модуля.
 */
export interface PracticalModuleResponse {
  id: string;
  slug: string;
  name: string;
  description: string;
  practiceType: string;
  basePath: string;
  identityAudience: string;
  isEnabled: boolean;
  configuration: string;
}
