/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ExternalModuleBindingResponse } from './externalModuleBindingResponse';

/**
 * Детали практики: вид, лимиты и привязка к внешнему модулю.
 */
export interface PracticalDetailResponse {
  id: string;
  name: string;
  kind: string;
  isPublic: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  triesCount: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  timeLimitMinutes: number | string | null;
  moduleBinding: null | ExternalModuleBindingResponse;
}
