/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SelectableQuestionResponse } from './selectableQuestionResponse';

/**
 * Данные для настройки теста практического материала.
 */
export interface PracticalQuestionsSetupResponse {
  questions: SelectableQuestionResponse[];
  isPublic: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  triesCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  percentForFive: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  percentForFour: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  percentForThree: number | string;
}
