/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Роль, назначаемая учебному профилю при связывании с identity-пользователем.
 */
export type ProfileRole = typeof ProfileRole[keyof typeof ProfileRole];


export const ProfileRole = {
  Student: 'Student',
  Teacher: 'Teacher',
  Admin: 'Admin',
} as const;
