/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные вопроса тестирования, возвращаемые API системы обучения.
 */
export interface QuestionResponse {
  id: string;
  text: string;
  type: string;
  weight: number;
  answer: string;
}
