/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Вопрос с признаком выбора для практического материала.
 */
export interface SelectableQuestionResponse {
  id: string;
  text: string;
  type: string;
  body: string;
  weight: number;
  isSelected: boolean;
}
