/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные начатой или продолженной попытки тестирования.
 */
export interface StartTestResponse {
  tryNumber: number;
}
