/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Ответ запуска: адрес перехода в модуль и метаданные попытки.
 */
export interface StartModuleSessionResponse {
  sessionId: string;
  launchUrl: string;
  /** @nullable */
  expiresAt: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  tryNumber: number | string;
  resumed: boolean;
}
