/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Студент в постраничном списке назначения на курс или практический материал.
 */
export interface StudentAssignmentEntryResponse {
  /** Идентификатор пользователя в учебной системе. */
  legacyUserId: string;
  /** Полное имя пользователя. */
  fullName: string;
  /** Логин пользователя — отличает однофамильцев. */
  login: string;
  /** Признак текущего назначения. */
  isAssigned: boolean;
  /**
     * Учебная группа или `null`, если не задана.
     * @nullable
     */
  group?: string | null;
}
