/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Учебная группа студентов.
 */
export interface StudentGroupResponse {
  /** Название группы. */
  name: string;
  /** Число привязанных студентов в группе. */
  studentsCount: number;
}
