/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { StudentAssignmentEntryResponse } from './studentAssignmentEntryResponse';

/**
 * Страница студентов для назначения на курс или практический материал.
 */
export interface StudentAssignmentPageResponse {
  /** Студенты запрошенной страницы, отсортированные по фамилии и имени. */
  items: StudentAssignmentEntryResponse[];
  /** Число студентов, подходящих под поиск и фильтр. */
  totalCount: number;
  /** Число всех назначенных студентов — не зависит от поиска и фильтра. */
  assignedCount: number;
  /** Номер возвращённой страницы, начиная с 1. */
  page: number;
  /** Размер страницы. */
  pageSize: number;
}
