/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Ответ студента на вопрос тестирования.
 */
export interface SubmitAnswerRequest {
  id: string;
  answer: string;
}
