/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitAnswerRequest } from './submitAnswerRequest';

/**
 * Запрос на отправку ответов текущей попытки тестирования.
 */
export interface SubmitTestRequest {
  answers: SubmitAnswerRequest[];
}
