/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Комментарий к файлу сдачи задания.
 */
export interface TaskFileCommentResponse {
  /** Идентификатор комментария. */
  id: string;
  /** Текст комментария. */
  text: string;
  /** Дата и время создания комментария. */
  created: string;
  /** Признак системного комментария. */
  isGenerated: boolean;
}
