/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TaskFileCommentResponse } from './taskFileCommentResponse';

/**
 * Данные файла сдачи задания.
 */
export interface TaskFileResponse {
  /** Идентификатор файла сдачи. */
  id: string;
  /** Серверный ключ файла для скачивания через API. */
  storageKey: string;
  /** Исходное имя файла. */
  name: string;
  /** Идентификатор студента, загрузившего файл. */
  userId: string;
  /** Полное имя студента. */
  fullName: string;
  /** Признак принятой сдачи. */
  isAccepted: boolean;
  /** Признак последнего системного обновления файла. */
  isUpdated: boolean;
  /**
     * Оценка за сдачу.
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  grade: number | string;
  /** Комментарии к файлу сдачи. */
  comments: TaskFileCommentResponse[];
}
