/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные задания практического материала.
 */
export interface TaskResponse {
  id: string;
  name: string;
  text: string;
}
