/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TestProtocolAnswerResponse } from './testProtocolAnswerResponse';

/**
 * Подробные данные протокола попытки тестирования.
 */
export interface TestProtocolResponse {
  answers: TestProtocolAnswerResponse[];
  tryNumber: number;
  /** @nullable */
  score: number | null;
  /** @nullable */
  maxScore: number | null;
  grade: number;
}
