/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Состояние текущей попытки тестирования.
 */
export interface TestStatusResponse {
  isStarted: boolean;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  tryNumber: number | string | null;
}
