/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TestQuestionResponse } from './testQuestionResponse';

/**
 * Список вопросов текущей попытки тестирования.
 */
export interface TestQuestionsResponse {
  questions: TestQuestionResponse[];
  isCompleted: boolean;
}
