/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Детализация ответа в протоколе попытки тестирования.
 */
export interface TestProtocolAnswerResponse {
  questionId: string;
  questionText: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  questionWeight: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  questionScore: number | string;
  userAnswer: string;
  isCorrect: boolean;
}
