/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Детализация ответа в протоколе попытки тестирования.
 */
export interface TestProtocolAnswerResponse {
  questionId: string;
  questionText: string;
  questionWeight: number;
  questionScore: number;
  userAnswer: string;
  isCorrect: boolean;
}
