/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Краткие данные протокола попытки тестирования.
 */
export interface TestProtocolSummaryResponse {
  id: string;
  userId: string;
  /** @nullable */
  score: number | null;
  /** @nullable */
  maxScore: number | null;
  tryNumber: number;
  grade: number;
}
