/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TestProtocolAnswerResponse } from './testProtocolAnswerResponse';

/**
 * Подробные данные протокола попытки тестирования.
 */
export interface TestProtocolResponse {
  answers: TestProtocolAnswerResponse[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  tryNumber: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  score: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  maxScore: number | string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  grade: number | string;
}
