/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Краткие данные протокола попытки тестирования.
 */
export interface TestProtocolSummaryResponse {
  id: string;
  userId: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  score: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
  maxScore: number | string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  tryNumber: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  grade: number | string;
}
