/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Вопрос, выдаваемый студенту в текущей попытке тестирования.
 */
export interface TestQuestionResponse {
  id: string;
  text: string;
  type: string;
  body: string;
}
