/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Текст теоретического материала, возвращаемый API системы обучения.
 */
export interface TheoryTextResponse {
  text: string;
  name: string;
}
