/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные ссылки теоретического материала, возвращаемые API системы обучения.
 */
export interface TheoryLinkResponse {
  id: string;
  link: string;
  description: string;
}
