/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Краткие данные теоретического материала для списков внутри модуля.
 */
export interface TheoryListItemResponse {
  id: string;
  name: string;
}
