/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Данные документа теоретического материала, возвращаемые API системы обучения.
 */
export interface TheoryDocumentResponse {
  id: string;
  path: string;
  description: string;
  name: string;
}
