/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на обновление отображаемых данных локального учебного профиля.
 */
export interface UpdateAdminProfileRequest {
  /** Отображаемый логин или имя пользователя. */
  login: string;
  /** Имя пользователя. */
  firstName: string;
  /** Фамилия пользователя. */
  lastName: string;
  /** Отчество пользователя. */
  middleName: string;
  /**
     * Учебная группа (до 50 символов); пусто или отсутствие значения снимает группу.
     * @nullable
     */
  group?: string | null;
}
