/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на изменение записи реестра практического модуля. Slug не меняется.
 */
export interface UpdatePracticalModuleRequest {
  name: string;
  description: string;
  practiceType: string;
  basePath: string;
  identityAudience: string;
  /** @nullable */
  configuration: string | null;
  isEnabled: boolean;
}
