/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на обновление текста задания практического материала.
 */
export interface UpdateTaskTextRequest {
  text: string;
}
