/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Запрос на обновление набора студентов, назначенных на практический материал.
 */
export interface UpdatePracticalStudentsRequest {
  /** Полный желаемый набор идентификаторов студентов учебной системы. */
  userIds: string[];
}
