/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from './iFormFile';

export type UploadStudentTaskFileBody = {
  file: IFormFile;
};
