/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CourseResponse,
  CreateCourseRequest,
  HttpValidationProblemDetails,
  ModuleResponse
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getTeacherCoursesResponse200 = {
  data: CourseResponse[]
  status: 200
}

export type getTeacherCoursesResponse401 = {
  data: void
  status: 401
}

export type getTeacherCoursesResponse403 = {
  data: void
  status: 403
}

export type getTeacherCoursesResponseSuccess = (getTeacherCoursesResponse200) & {
  headers: Headers;
};
export type getTeacherCoursesResponseError = (getTeacherCoursesResponse401 | getTeacherCoursesResponse403) & {
  headers: Headers;
};

export type getTeacherCoursesResponse = (getTeacherCoursesResponseSuccess | getTeacherCoursesResponseError)

export const getGetTeacherCoursesUrl = () => {




  return `/api/v1/courses/teacher`
}

/**
 * Возвращает список курсов, доступных текущему преподавателю.
 * @summary Получение курсов преподавателя
 */
export const getTeacherCourses = async ( options?: Parameters<typeof educationFetch>[1]): Promise<getTeacherCoursesResponse> => {

  return educationFetch<getTeacherCoursesResponse>(getGetTeacherCoursesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTeacherCoursesQueryKey = () => {
    return [
    `/api/v1/courses/teacher`
    ] as const;
    }


export const getGetTeacherCoursesQueryOptions = <TData = Awaited<ReturnType<typeof getTeacherCourses>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherCourses>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeacherCoursesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeacherCourses>>> = ({ signal }) => getTeacherCourses({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeacherCourses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTeacherCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getTeacherCourses>>>
export type GetTeacherCoursesQueryError = void


export function useGetTeacherCourses<TData = Awaited<ReturnType<typeof getTeacherCourses>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherCourses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherCourses>>,
          TError,
          Awaited<ReturnType<typeof getTeacherCourses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherCourses<TData = Awaited<ReturnType<typeof getTeacherCourses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherCourses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherCourses>>,
          TError,
          Awaited<ReturnType<typeof getTeacherCourses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherCourses<TData = Awaited<ReturnType<typeof getTeacherCourses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherCourses>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение курсов преподавателя
 */

export function useGetTeacherCourses<TData = Awaited<ReturnType<typeof getTeacherCourses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherCourses>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeacherCoursesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getStudentCoursesResponse200 = {
  data: CourseResponse[]
  status: 200
}

export type getStudentCoursesResponse401 = {
  data: void
  status: 401
}

export type getStudentCoursesResponse403 = {
  data: void
  status: 403
}

export type getStudentCoursesResponseSuccess = (getStudentCoursesResponse200) & {
  headers: Headers;
};
export type getStudentCoursesResponseError = (getStudentCoursesResponse401 | getStudentCoursesResponse403) & {
  headers: Headers;
};

export type getStudentCoursesResponse = (getStudentCoursesResponseSuccess | getStudentCoursesResponseError)

export const getGetStudentCoursesUrl = () => {




  return `/api/v1/courses/student`
}

/**
 * Возвращает список курсов, назначенных текущему студенту.
 * @summary Получение курсов студента
 */
export const getStudentCourses = async ( options?: Parameters<typeof educationFetch>[1]): Promise<getStudentCoursesResponse> => {

  return educationFetch<getStudentCoursesResponse>(getGetStudentCoursesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentCoursesQueryKey = () => {
    return [
    `/api/v1/courses/student`
    ] as const;
    }


export const getGetStudentCoursesQueryOptions = <TData = Awaited<ReturnType<typeof getStudentCourses>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentCourses>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentCoursesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentCourses>>> = ({ signal }) => getStudentCourses({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentCourses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentCourses>>>
export type GetStudentCoursesQueryError = void


export function useGetStudentCourses<TData = Awaited<ReturnType<typeof getStudentCourses>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentCourses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentCourses>>,
          TError,
          Awaited<ReturnType<typeof getStudentCourses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentCourses<TData = Awaited<ReturnType<typeof getStudentCourses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentCourses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentCourses>>,
          TError,
          Awaited<ReturnType<typeof getStudentCourses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentCourses<TData = Awaited<ReturnType<typeof getStudentCourses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentCourses>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение курсов студента
 */

export function useGetStudentCourses<TData = Awaited<ReturnType<typeof getStudentCourses>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentCourses>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentCoursesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createCourseResponse200 = {
  data: CourseResponse
  status: 200
}

export type createCourseResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createCourseResponse401 = {
  data: void
  status: 401
}

export type createCourseResponse403 = {
  data: void
  status: 403
}

export type createCourseResponseSuccess = (createCourseResponse200) & {
  headers: Headers;
};
export type createCourseResponseError = (createCourseResponse400 | createCourseResponse401 | createCourseResponse403) & {
  headers: Headers;
};

export type createCourseResponse = (createCourseResponseSuccess | createCourseResponseError)

export const getCreateCourseUrl = () => {




  return `/api/v1/courses`
}

/**
 * Создаёт новый курс от имени текущего преподавателя.
 * @summary Создание курса
 */
export const createCourse = async (createCourseRequest: CreateCourseRequest, options?: Parameters<typeof educationFetch>[1]): Promise<createCourseResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return educationFetch<createCourseResponse>(getCreateCourseUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createCourseRequest)
  }
);}





export const getCreateCourseMutationKey = () => ['createCourse'] as const;

export const getCreateCourseMutationOptions = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourse>>, TError,CreateCourseMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCourse>>, TError,CreateCourseMutationVariables, TContext> => {

const mutationKey = getCreateCourseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCourse>>, CreateCourseMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createCourse(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof createCourse>>>
    export type CreateCourseMutationBody = CreateCourseRequest
    export type CreateCourseMutationError = HttpValidationProblemDetails | void
    export type CreateCourseMutationVariables = {data: CreateCourseRequest}

    /**
 * @summary Создание курса
 */
export const useCreateCourse = <TError = HttpValidationProblemDetails | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCourse>>, TError,CreateCourseMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCourse>>,
        TError,
        CreateCourseMutationVariables,
        TContext
      > => {
      return useMutation(getCreateCourseMutationOptions(options), queryClient);
    }
    export type deleteCourseResponse204 = {
  data: void
  status: 204
}

export type deleteCourseResponse401 = {
  data: void
  status: 401
}

export type deleteCourseResponse403 = {
  data: void
  status: 403
}

export type deleteCourseResponse404 = {
  data: void
  status: 404
}

export type deleteCourseResponseSuccess = (deleteCourseResponse204) & {
  headers: Headers;
};
export type deleteCourseResponseError = (deleteCourseResponse401 | deleteCourseResponse403 | deleteCourseResponse404) & {
  headers: Headers;
};

export type deleteCourseResponse = (deleteCourseResponseSuccess | deleteCourseResponseError)

export const getDeleteCourseUrl = (courseId: string,) => {




  return `/api/v1/courses/${courseId}`
}

/**
 * Удаляет курс, если он принадлежит текущему преподавателю.
 * @summary Удаление курса
 */
export const deleteCourse = async (courseId: string, options?: Parameters<typeof educationFetch>[1]): Promise<deleteCourseResponse> => {

  return educationFetch<deleteCourseResponse>(getDeleteCourseUrl(courseId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCourseMutationKey = () => ['deleteCourse'] as const;

export const getDeleteCourseMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourse>>, TError,DeleteCourseMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCourse>>, TError,DeleteCourseMutationVariables, TContext> => {

const mutationKey = getDeleteCourseMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCourse>>, DeleteCourseMutationVariables> = (props) => {
          const {courseId} = props ?? {};

          return  deleteCourse(courseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCourseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCourse>>>

    export type DeleteCourseMutationError = void
    export type DeleteCourseMutationVariables = {courseId: string}

    /**
 * @summary Удаление курса
 */
export const useDeleteCourse = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCourse>>, TError,DeleteCourseMutationVariables, TContext>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCourse>>,
        TError,
        DeleteCourseMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteCourseMutationOptions(options), queryClient);
    }
    export type getCourseModulesResponse200 = {
  data: ModuleResponse[]
  status: 200
}

export type getCourseModulesResponse401 = {
  data: void
  status: 401
}

export type getCourseModulesResponse403 = {
  data: void
  status: 403
}

export type getCourseModulesResponseSuccess = (getCourseModulesResponse200) & {
  headers: Headers;
};
export type getCourseModulesResponseError = (getCourseModulesResponse401 | getCourseModulesResponse403) & {
  headers: Headers;
};

export type getCourseModulesResponse = (getCourseModulesResponseSuccess | getCourseModulesResponseError)

export const getGetCourseModulesUrl = (courseId: string,) => {




  return `/api/v1/courses/${courseId}/modules`
}

/**
 * Возвращает модули выбранного курса.
 * @summary Получение модулей курса
 */
export const getCourseModules = async (courseId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getCourseModulesResponse> => {

  return educationFetch<getCourseModulesResponse>(getGetCourseModulesUrl(courseId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCourseModulesQueryKey = (courseId: string,) => {
    return [
    `/api/v1/courses/${courseId}/modules`
    ] as const;
    }


export const getGetCourseModulesQueryOptions = <TData = Awaited<ReturnType<typeof getCourseModules>>, TError = void>(courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseModules>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCourseModulesQueryKey(courseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourseModules>>> = ({ signal }) => getCourseModules(courseId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: courseId !== null && courseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourseModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCourseModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getCourseModules>>>
export type GetCourseModulesQueryError = void


export function useGetCourseModules<TData = Awaited<ReturnType<typeof getCourseModules>>, TError = void>(
 courseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourseModules>>,
          TError,
          Awaited<ReturnType<typeof getCourseModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourseModules<TData = Awaited<ReturnType<typeof getCourseModules>>, TError = void>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourseModules>>,
          TError,
          Awaited<ReturnType<typeof getCourseModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourseModules<TData = Awaited<ReturnType<typeof getCourseModules>>, TError = void>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseModules>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение модулей курса
 */

export function useGetCourseModules<TData = Awaited<ReturnType<typeof getCourseModules>>, TError = void>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseModules>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCourseModulesQueryOptions(courseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






