/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PracticalGradeResponse
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPracticalGradeResponse200 = {
  data: PracticalGradeResponse
  status: 200
}

export type getPracticalGradeResponse401 = {
  data: void
  status: 401
}

export type getPracticalGradeResponse403 = {
  data: void
  status: 403
}

export type getPracticalGradeResponseSuccess = (getPracticalGradeResponse200) & {
  headers: Headers;
};
export type getPracticalGradeResponseError = (getPracticalGradeResponse401 | getPracticalGradeResponse403) & {
  headers: Headers;
};

export type getPracticalGradeResponse = (getPracticalGradeResponseSuccess | getPracticalGradeResponseError)

export const getGetPracticalGradeUrl = (practicalId: string,) => {




  return `/api/v1/practicals/${practicalId}/grade`
}

/**
 * Возвращает итоговую оценку и поясняющие сообщения по практическому заданию студента.
 * @summary Получение оценки за практику
 */
export const getPracticalGrade = async (practicalId: string, options?: Parameters<typeof educationFetch>[1]): Promise<getPracticalGradeResponse> => {

  return educationFetch<getPracticalGradeResponse>(getGetPracticalGradeUrl(practicalId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPracticalGradeQueryKey = (practicalId: string,) => {
    return [
    `/api/v1/practicals/${practicalId}/grade`
    ] as const;
    }


export const getGetPracticalGradeQueryOptions = <TData = Awaited<ReturnType<typeof getPracticalGrade>>, TError = void>(practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalGrade>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPracticalGradeQueryKey(practicalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPracticalGrade>>> = ({ signal }) => getPracticalGrade(practicalId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: practicalId !== null && practicalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPracticalGrade>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPracticalGradeQueryResult = NonNullable<Awaited<ReturnType<typeof getPracticalGrade>>>
export type GetPracticalGradeQueryError = void


export function useGetPracticalGrade<TData = Awaited<ReturnType<typeof getPracticalGrade>>, TError = void>(
 practicalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalGrade>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalGrade>>,
          TError,
          Awaited<ReturnType<typeof getPracticalGrade>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalGrade<TData = Awaited<ReturnType<typeof getPracticalGrade>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalGrade>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPracticalGrade>>,
          TError,
          Awaited<ReturnType<typeof getPracticalGrade>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPracticalGrade<TData = Awaited<ReturnType<typeof getPracticalGrade>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalGrade>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение оценки за практику
 */

export function useGetPracticalGrade<TData = Awaited<ReturnType<typeof getPracticalGrade>>, TError = void>(
 practicalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPracticalGrade>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPracticalGradeQueryOptions(practicalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






