/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ProblemDetails
} from '../model';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type downloadFileResponse200 = {
  data: void
  status: 200
}

export type downloadFileResponse400 = {
  data: ProblemDetails
  status: 400
}

export type downloadFileResponse401 = {
  data: void
  status: 401
}

export type downloadFileResponse403 = {
  data: void
  status: 403
}

export type downloadFileResponse404 = {
  data: void
  status: 404
}

export type downloadFileResponseSuccess = (downloadFileResponse200) & {
  headers: Headers;
};
export type downloadFileResponseError = (downloadFileResponse400 | downloadFileResponse401 | downloadFileResponse403 | downloadFileResponse404) & {
  headers: Headers;
};

export type downloadFileResponse = (downloadFileResponseSuccess | downloadFileResponseError)

export const getDownloadFileUrl = (storageKey: string,) => {




  return `/api/v1/files/${storageKey}`
}

/**
 * Возвращает файл из хранилища по ключу, если текущий пользователь имеет к нему доступ.
 * @summary Скачивание файла
 */
export const downloadFile = async (storageKey: string, options?: Parameters<typeof educationFetch>[1]): Promise<downloadFileResponse> => {

  return educationFetch<downloadFileResponse>(getDownloadFileUrl(storageKey),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownloadFileQueryKey = (storageKey: string,) => {
    return [
    `/api/v1/files/${storageKey}`
    ] as const;
    }


export const getDownloadFileQueryOptions = <TData = Awaited<ReturnType<typeof downloadFile>>, TError = ProblemDetails | void>(storageKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadFileQueryKey(storageKey);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({ signal }) => downloadFile(storageKey, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: storageKey !== null && storageKey !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadFileQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFile>>>
export type DownloadFileQueryError = ProblemDetails | void


export function useDownloadFile<TData = Awaited<ReturnType<typeof downloadFile>>, TError = ProblemDetails | void>(
 storageKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFile<TData = Awaited<ReturnType<typeof downloadFile>>, TError = ProblemDetails | void>(
 storageKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFile>>,
          TError,
          Awaited<ReturnType<typeof downloadFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFile<TData = Awaited<ReturnType<typeof downloadFile>>, TError = ProblemDetails | void>(
 storageKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Скачивание файла
 */

export function useDownloadFile<TData = Awaited<ReturnType<typeof downloadFile>>, TError = ProblemDetails | void>(
 storageKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadFileQueryOptions(storageKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






