/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Education.Web | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { educationFetch } from '../../../shared/http/education-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiV1StudentPingResponse200 = {
  data: void
  status: 200
}

export type getApiV1StudentPingResponse401 = {
  data: void
  status: 401
}

export type getApiV1StudentPingResponse403 = {
  data: void
  status: 403
}

export type getApiV1StudentPingResponseSuccess = (getApiV1StudentPingResponse200) & {
  headers: Headers;
};
export type getApiV1StudentPingResponseError = (getApiV1StudentPingResponse401 | getApiV1StudentPingResponse403) & {
  headers: Headers;
};

export type getApiV1StudentPingResponse = (getApiV1StudentPingResponseSuccess | getApiV1StudentPingResponseError)

export const getGetApiV1StudentPingUrl = () => {




  return `/api/v1/student/ping`
}

/**
 * Проверяет, что Bearer-токен содержит роль Student.
 * @summary Проверка доступа студента
 */
export const getApiV1StudentPing = async ( options?: Parameters<typeof educationFetch>[1]): Promise<getApiV1StudentPingResponse> => {

  return educationFetch<getApiV1StudentPingResponse>(getGetApiV1StudentPingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1StudentPingQueryKey = () => {
    return [
    `/api/v1/student/ping`
    ] as const;
    }


export const getGetApiV1StudentPingQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1StudentPing>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1StudentPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1StudentPingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1StudentPing>>> = ({ signal }) => getApiV1StudentPing({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1StudentPing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1StudentPingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1StudentPing>>>
export type GetApiV1StudentPingQueryError = void


export function useGetApiV1StudentPing<TData = Awaited<ReturnType<typeof getApiV1StudentPing>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1StudentPing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1StudentPing>>,
          TError,
          Awaited<ReturnType<typeof getApiV1StudentPing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1StudentPing<TData = Awaited<ReturnType<typeof getApiV1StudentPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1StudentPing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1StudentPing>>,
          TError,
          Awaited<ReturnType<typeof getApiV1StudentPing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1StudentPing<TData = Awaited<ReturnType<typeof getApiV1StudentPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1StudentPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Проверка доступа студента
 */

export function useGetApiV1StudentPing<TData = Awaited<ReturnType<typeof getApiV1StudentPing>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1StudentPing>>, TError, TData>>, request?: SecondParameter<typeof educationFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1StudentPingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






